apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lc-classifier-step.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  consumer-group: {{ .Values.configmap.consumerGroup | default (printf "%s" (include "lc-classifier-step.fullname" .)) }}
  internal-server: {{ .Values.configmap.internalServer }}
  public-server: {{ .Values.configmap.publicServer }}
  scribe-topic: {{ .Values.configmap.scribeTopic }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}
  consume-timeout: "{{ .Values.configmap.consumeTimeout }}"
  consume-messages: "{{ .Values.configmap.consumeMessages }}"
  kafka-producer-security-protocol: {{ .Values.configmap.kafka.securityProtocol }}
  kafka-producer-sasl-mechanism: {{ .Values.configmap.kafka.saslMechanism }}
  stream: {{ .Values.configmap.stream }}
  model-version: {{ .Values.configmap.modelVersion }}
  model-path: "{{ .Values.configmap.modelPath }}"
  quantiles-path: "{{ .Values.configmap.quantilesPath }}"
  feature-quantiles-path: "{{ .Values.configmap.featureQuantilesPath }}"
  model-class: {{ .Values.configmap.modelClass }}
  mapper-class: {{ .Values.configmap.mapperClass }}
  scribe-parser-class: {{ .Values.configmap.scribeParserClass }}
  step-parser-class: {{ .Values.configmap.stepParserClass }}
  producer-class: {{ .Values.configmap.producerClass }}
  producer-topic-format: {{ .Values.configmap.producerTopicFormat }}
  producer-date-format: "{{ .Values.configmap.producerDateFormat }}"
  producer-change-hour: "{{ .Values.configmap.producerChangeHour }}"
