DETECTIONS = {
    "type": "array",
    "default": [],
    "items": {
        "name": "detections_record",
        "type": "record",
        "fields": [
            {
                "name": "candid",
                "type": "int",
                "description": "integer just for test purposes",
            },
            {"name": "tid", "type": "string"},
            {"name": "aid", "type": "string"},
            {"name": "oid", "type": "int", "description": "int just for test purposes"},
            {"name": "fid", "type": "string"},
            {"name": "mjd", "type": "double"},
            {"name": "mag", "type": "float"},
            {"name": "e_mag", "type": "float"},
            {"name": "has_stamp", "type": "boolean"},
            {"name": "forced", "type": "boolean"},
            {"name": "new", "type": "boolean"},
            {"name": "parent_candid", "type": ["long", "string", "null"]},
            {
                "name": "extra_fields",
                "type": {
                    "default": {},
                    "type": "map",
                    "values": [
                        "null",
                        "int",
                        "float",
                        "string",
                        "bytes",
                        "boolean",
                    ],
                },
            },
        ],
    },
}

NON_DETECTIONS = {
    "type": "array",
    "default": [],
    "items": {
        "name": "non_detections_record",
        "type": "map",
        "values": [
            "string",
            "double",
            "float",
        ],
    },
}

XMATCH = {
    "type": "map",
    "values": {"type": "map", "values": ["string", "float", "null", "int"]},
}

FEATURES_SCHEMA = {
    "name": "features_record",
    "type": "record",
    "fields": [
        {"name": "Mean_i", "type": ["float", "null"]},
        {"name": "SPM_chi_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_z", "type": ["float", "null"]},
        {"name": "SPM_A_i", "type": ["float", "null"]},
        {"name": "max_flux_after_band_i", "type": ["float", "null"]},
        {"name": "SPM_chi_z", "type": ["float", "null"]},
        {"name": "Std_u", "type": ["float", "null"]},
        {"name": "Autocor_length_g", "type": ["float", "null"]},
        {"name": "g-r", "type": ["float", "null"]},
        {"name": "Autocor_length_i", "type": ["float", "null"]},
        {"name": "MaxSlope_r", "type": ["float", "null"]},
        {"name": "SPM_chi_g", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_Y", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_g", "type": ["float", "null"]},
        {"name": "LinearTrend_r", "type": ["float", "null"]},
        {"name": "MHPS_low_r", "type": ["float", "null"]},
        {"name": "SPM_t0_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_i", "type": ["float", "null"]},
        {"name": "positive_fraction_r", "type": ["float", "null"]},
        {"name": "i-z", "type": ["float", "null"]},
        {"name": "SPM_chi_r", "type": ["float", "null"]},
        {"name": "Rcs_i", "type": ["float", "null"]},
        {"name": "SPM_A_r", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_i", "type": ["float", "null"]},
        {"name": "Autocor_length_r", "type": ["float", "null"]},
        {"name": "SPM_A_Y", "type": ["float", "null"]},
        {"name": "MHPS_low_z", "type": ["float", "null"]},
        {"name": "SPM_A_g", "type": ["float", "null"]},
        {"name": "ExcessVar_Y", "type": ["float", "null"]},
        {"name": "Harmonics_mse_r", "type": ["float", "null"]},
        {"name": "SPM_chi_u", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_z", "type": ["float", "null"]},
        {"name": "Skew_r", "type": ["float", "null"]},
        {"name": "IAR_phi_g", "type": ["float", "null"]},
        {"name": "Harmonics_mse_z", "type": ["float", "null"]},
        {"name": "positive_fraction_i", "type": ["float", "null"]},
        {"name": "Harmonics_mse_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_z", "type": ["float", "null"]},
        {"name": "ExcessVar_z", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_Y", "type": ["float", "null"]},
        {"name": "AndersonDarling_r", "type": ["float", "null"]},
        {"name": "SPM_t0_i", "type": ["float", "null"]},
        {"name": "positive_fraction_z", "type": ["float", "null"]},
        {"name": "ExcessVar_g", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_r", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_z", "type": ["float", "null"]},
        {"name": "positive_fraction_g", "type": ["float", "null"]},
        {"name": "MHPS_high_z", "type": ["float", "null"]},
        {"name": "Rcs_g", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_z", "type": ["float", "null"]},
        {"name": "Eta_e_u", "type": ["float", "null"]},
        {"name": "IAR_phi_r", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_g", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_r", "type": ["float", "null"]},
        {"name": "MaxSlope_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_r", "type": ["float", "null"]},
        {"name": "Gskew_r", "type": ["float", "null"]},
        {"name": "SPM_t0_z", "type": ["float", "null"]},
        {"name": "Meanvariance_r", "type": ["float", "null"]},
        {"name": "MHPS_high_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_g", "type": ["float", "null"]},
        {"name": "AndersonDarling_i", "type": ["float", "null"]},
        {"name": "SPM_t0_Y", "type": ["float", "null"]},
        {"name": "IAR_phi_z", "type": ["float", "null"]},
        {"name": "Gskew_i", "type": ["float", "null"]},
        {"name": "Amplitude_r", "type": ["float", "null"]},
        {"name": "Amplitude_g", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_r", "type": ["float", "null"]},
        {"name": "MaxSlope_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_g", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_u", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_r", "type": ["float", "null"]},
        {"name": "Rcs_r", "type": ["float", "null"]},
        {"name": "mwebv", "type": ["float", "null"]},
        {"name": "Std_r", "type": ["float", "null"]},
        {"name": "IAR_phi_i", "type": ["float", "null"]},
        {"name": "ExcessVar_r", "type": ["float", "null"]},
        {"name": "r-i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_i", "type": ["float", "null"]},
        {"name": "SPM_A_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_g", "type": ["float", "null"]},
        {"name": "MHPS_high_i", "type": ["float", "null"]},
        {"name": "Rcs_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_i", "type": ["float", "null"]},
        {"name": "ExcessVar_i", "type": ["float", "null"]},
        {"name": "Mean_r", "type": ["float", "null"]},
        {"name": "SPM_t0_r", "type": ["float", "null"]},
        {"name": "MHPS_low_i", "type": ["float", "null"]},
        {"name": "SPM_t0_u", "type": ["float", "null"]},
        {"name": "redshift_helio", "type": ["float", "null"]},
        {"name": "u-g", "type": ["float", "null"]},
        {"name": "LinearTrend_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_r", "type": ["float", "null"]},
        {"name": "Power_rate_4", "type": ["float", "null"]},
        {"name": "Power_rate_1/2", "type": ["float", "null"]},
        {"name": "Mean_i", "type": ["float", "null"]},
        {"name": "z-Y", "type": ["float", "null"]},
        {"name": "last_flux_before_band_r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_z", "type": ["float", "null"]},
        {"name": "SPM_chi_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_z", "type": ["float", "null"]},
        {"name": "SPM_A_i", "type": ["float", "null"]},
        {"name": "max_flux_after_band_i", "type": ["float", "null"]},
        {"name": "SPM_chi_z", "type": ["float", "null"]},
        {"name": "Std_u", "type": ["float", "null"]},
        {"name": "Autocor_length_g", "type": ["float", "null"]},
        {"name": "median_flux_before_band_i", "type": ["float", "null"]},
        {"name": "max_flux_before_band_Y", "type": ["float", "null"]},
        {"name": "g-r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_i", "type": ["float", "null"]},
        {"name": "Power_rate_3", "type": ["float", "null"]},
        {"name": "PercentAmplitude_z", "type": ["float", "null"]},
        {"name": "MaxSlope_r", "type": ["float", "null"]},
        {"name": "SPM_chi_g", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_2", "type": ["float", "null"]},
        {"name": "last_flux_before_band_z", "type": ["float", "null"]},
        {"name": "last_flux_before_band_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_Y", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_g", "type": ["float", "null"]},
        {"name": "LinearTrend_r", "type": ["float", "null"]},
        {"name": "MHPS_low_r", "type": ["float", "null"]},
        {"name": "SPM_t0_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_i", "type": ["float", "null"]},
        {"name": "positive_fraction_r", "type": ["float", "null"]},
        {"name": "i-z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_u", "type": ["float", "null"]},
        {"name": "SmallKurtosis_z", "type": ["float", "null"]},
        {"name": "SPM_chi_r", "type": ["float", "null"]},
        {"name": "Rcs_i", "type": ["float", "null"]},
        {"name": "SPM_A_r", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/4", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_u", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_i", "type": ["float", "null"]},
        {"name": "median_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_u", "type": ["float", "null"]},
        {"name": "SPM_A_Y", "type": ["float", "null"]},
        {"name": "MHPS_low_z", "type": ["float", "null"]},
        {"name": "SPM_A_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_i", "type": ["float", "null"]},
        {"name": "ExcessVar_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/3", "type": ["float", "null"]},
        {"name": "Harmonics_mse_r", "type": ["float", "null"]},
        {"name": "SPM_chi_u", "type": ["float", "null"]},
        {"name": "Amplitude_i", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_z", "type": ["float", "null"]},
        {"name": "Std_z", "type": ["float", "null"]},
        {"name": "Skew_r", "type": ["float", "null"]},
        {"name": "IAR_phi_g", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_r", "type": ["float", "null"]},
        {"name": "Harmonics_mse_z", "type": ["float", "null"]},
        {"name": "positive_fraction_i", "type": ["float", "null"]},
        {"name": "Harmonics_mse_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_z", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_i", "type": ["float", "null"]},
        {"name": "ExcessVar_z", "type": ["float", "null"]},
        {"name": "Std_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_g", "type": ["float", "null"]},
        {"name": "Meanvariance_z", "type": ["float", "null"]},
        {"name": "median_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_Y", "type": ["float", "null"]},
        {"name": "median_flux_before_band_r", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_r", "type": ["float", "null"]},
        {"name": "AndersonDarling_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_Y", "type": ["float", "null"]},
        {"name": "SPM_t0_i", "type": ["float", "null"]},
        {"name": "positive_fraction_z", "type": ["float", "null"]},
        {"name": "ExcessVar_g", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_z", "type": ["float", "null"]},
        {"name": "positive_fraction_g", "type": ["float", "null"]},
        {"name": "max_flux_before_band_z", "type": ["float", "null"]},
        {"name": "MHPS_high_z", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_z", "type": ["float", "null"]},
        {"name": "Rcs_g", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_z", "type": ["float", "null"]},
        {"name": "Eta_e_u", "type": ["float", "null"]},
        {"name": "IAR_phi_r", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_r", "type": ["float", "null"]},
        {"name": "MaxSlope_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_r", "type": ["float", "null"]},
        {"name": "LinearTrend_z", "type": ["float", "null"]},
        {"name": "Gskew_r", "type": ["float", "null"]},
        {"name": "SPM_t0_z", "type": ["float", "null"]},
        {"name": "Meanvariance_r", "type": ["float", "null"]},
        {"name": "MHPS_high_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_g", "type": ["float", "null"]},
        {"name": "AndersonDarling_i", "type": ["float", "null"]},
        {"name": "SPM_t0_Y", "type": ["float", "null"]},
        {"name": "IAR_phi_z", "type": ["float", "null"]},
        {"name": "Gskew_i", "type": ["float", "null"]},
        {"name": "Gskew_z", "type": ["float", "null"]},
        {"name": "max_flux_before_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_r", "type": ["float", "null"]},
        {"name": "Amplitude_g", "type": ["float", "null"]},
        {"name": "Mean_z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_r", "type": ["float", "null"]},
        {"name": "MaxSlope_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_g", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_u", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_i", "type": ["float", "null"]},
        {"name": "Amplitude_z", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_r", "type": ["float", "null"]},
        {"name": "Rcs_r", "type": ["float", "null"]},
        {"name": "mwebv", "type": ["float", "null"]},
        {"name": "Std_r", "type": ["float", "null"]},
        {"name": "IAR_phi_i", "type": ["float", "null"]},
        {"name": "ExcessVar_r", "type": ["float", "null"]},
        {"name": "r-i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_i", "type": ["float", "null"]},
        {"name": "Q31_z", "type": ["float", "null"]},
        {"name": "SPM_A_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_g", "type": ["float", "null"]},
        {"name": "MHPS_high_i", "type": ["float", "null"]},
        {"name": "median_flux_before_band_z", "type": ["float", "null"]},
        {"name": "max_flux_before_band_i", "type": ["float", "null"]},
        {"name": "Rcs_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_i", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_u", "type": ["float", "null"]},
        {"name": "ExcessVar_i", "type": ["float", "null"]},
        {"name": "Mean_r", "type": ["float", "null"]},
        {"name": "median_flux_after_band_u", "type": ["float", "null"]},
        {"name": "SPM_A_u", "type": ["float", "null"]},
        {"name": "SPM_t0_r", "type": ["float", "null"]},
        {"name": "MHPS_low_i", "type": ["float", "null"]},
        {"name": "SPM_t0_u", "type": ["float", "null"]},
        {"name": "redshift_helio", "type": ["float", "null"]},
        {"name": "u-g", "type": ["float", "null"]},
        {"name": "LinearTrend_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_r", "type": ["float", "null"]},
        {"name": "Power_rate_4", "type": ["float", "null"]},
        {"name": "Period_band_r", "type": ["float", "null"]},
        {"name": "Power_rate_1/2", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_r", "type": ["float", "null"]},
        {"name": "Mean_i", "type": ["float", "null"]},
        {"name": "Harmonics_mag_2_Y", "type": ["float", "null"]},
        {"name": "z-Y", "type": ["float", "null"]},
        {"name": "last_flux_before_band_r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_z", "type": ["float", "null"]},
        {"name": "SPM_chi_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_i", "type": ["float", "null"]},
        {"name": "SPM_A_i", "type": ["float", "null"]},
        {"name": "Skew_z", "type": ["float", "null"]},
        {"name": "Psi_eta_z", "type": ["float", "null"]},
        {"name": "SPM_chi_z", "type": ["float", "null"]},
        {"name": "Beyond1Std_z", "type": ["float", "null"]},
        {"name": "Std_u", "type": ["float", "null"]},
        {"name": "Q31_r", "type": ["float", "null"]},
        {"name": "MaxSlope_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_g", "type": ["float", "null"]},
        {"name": "Q31_i", "type": ["float", "null"]},
        {"name": "Beyond1Std_i", "type": ["float", "null"]},
        {"name": "median_flux_before_band_i", "type": ["float", "null"]},
        {"name": "max_flux_before_band_Y", "type": ["float", "null"]},
        {"name": "g-r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_i", "type": ["float", "null"]},
        {"name": "Std_g", "type": ["float", "null"]},
        {"name": "Power_rate_3", "type": ["float", "null"]},
        {"name": "PercentAmplitude_z", "type": ["float", "null"]},
        {"name": "SPM_chi_Y", "type": ["float", "null"]},
        {"name": "MaxSlope_r", "type": ["float", "null"]},
        {"name": "SPM_chi_g", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_2", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_g", "type": ["float", "null"]},
        {"name": "last_flux_before_band_z", "type": ["float", "null"]},
        {"name": "StetsonK_z", "type": ["float", "null"]},
        {"name": "last_flux_before_band_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_Y", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_g", "type": ["float", "null"]},
        {"name": "LinearTrend_r", "type": ["float", "null"]},
        {"name": "MHPS_low_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_z", "type": ["float", "null"]},
        {"name": "SPM_t0_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_i", "type": ["float", "null"]},
        {"name": "Std_Y", "type": ["float", "null"]},
        {"name": "positive_fraction_r", "type": ["float", "null"]},
        {"name": "Pvar_g", "type": ["float", "null"]},
        {"name": "i-z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_u", "type": ["float", "null"]},
        {"name": "SmallKurtosis_z", "type": ["float", "null"]},
        {"name": "Psi_eta_Y", "type": ["float", "null"]},
        {"name": "SPM_chi_r", "type": ["float", "null"]},
        {"name": "Rcs_i", "type": ["float", "null"]},
        {"name": "SPM_A_r", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/4", "type": ["float", "null"]},
        {"name": "Gskew_Y", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_u", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_i", "type": ["float", "null"]},
        {"name": "median_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_u", "type": ["float", "null"]},
        {"name": "SPM_A_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_Y", "type": ["float", "null"]},
        {"name": "MHPS_low_z", "type": ["float", "null"]},
        {"name": "SPM_A_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_i", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_z", "type": ["float", "null"]},
        {"name": "ExcessVar_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/3", "type": ["float", "null"]},
        {"name": "Harmonics_mse_r", "type": ["float", "null"]},
        {"name": "SPM_chi_u", "type": ["float", "null"]},
        {"name": "Amplitude_i", "type": ["float", "null"]},
        {"name": "Q31_u", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_z", "type": ["float", "null"]},
        {"name": "Std_z", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_i", "type": ["float", "null"]},
        {"name": "Skew_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_i", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_i", "type": ["float", "null"]},
        {"name": "IAR_phi_g", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_r", "type": ["float", "null"]},
        {"name": "Harmonics_mse_z", "type": ["float", "null"]},
        {"name": "positive_fraction_i", "type": ["float", "null"]},
        {"name": "Harmonics_mse_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_z", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_i", "type": ["float", "null"]},
        {"name": "MedianAbsDev_u", "type": ["float", "null"]},
        {"name": "ExcessVar_z", "type": ["float", "null"]},
        {"name": "Std_i", "type": ["float", "null"]},
        {"name": "Skew_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_z", "type": ["float", "null"]},
        {"name": "Meanvariance_z", "type": ["float", "null"]},
        {"name": "median_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_Y", "type": ["float", "null"]},
        {"name": "median_flux_before_band_r", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_Y", "type": ["float", "null"]},
        {"name": "AndersonDarling_r", "type": ["float", "null"]},
        {"name": "SPM_t0_i", "type": ["float", "null"]},
        {"name": "positive_fraction_z", "type": ["float", "null"]},
        {"name": "ExcessVar_g", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_z", "type": ["float", "null"]},
        {"name": "positive_fraction_g", "type": ["float", "null"]},
        {"name": "max_flux_before_band_z", "type": ["float", "null"]},
        {"name": "Period_band_z", "type": ["float", "null"]},
        {"name": "MHPS_high_z", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_z", "type": ["float", "null"]},
        {"name": "StetsonK_r", "type": ["float", "null"]},
        {"name": "Gskew_u", "type": ["float", "null"]},
        {"name": "Rcs_g", "type": ["float", "null"]},
        {"name": "MedianAbsDev_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_z", "type": ["float", "null"]},
        {"name": "Eta_e_u", "type": ["float", "null"]},
        {"name": "IAR_phi_r", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_Y", "type": ["float", "null"]},
        {"name": "Q31_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_r", "type": ["float", "null"]},
        {"name": "MaxSlope_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_r", "type": ["float", "null"]},
        {"name": "LinearTrend_z", "type": ["float", "null"]},
        {"name": "Gskew_r", "type": ["float", "null"]},
        {"name": "SPM_t0_z", "type": ["float", "null"]},
        {"name": "Multiband_period", "type": ["float", "null"]},
        {"name": "Meanvariance_r", "type": ["float", "null"]},
        {"name": "MHPS_high_r", "type": ["float", "null"]},
        {"name": "Pvar_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_g", "type": ["float", "null"]},
        {"name": "AndersonDarling_i", "type": ["float", "null"]},
        {"name": "Period_band_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_Y", "type": ["float", "null"]},
        {"name": "Skew_Y", "type": ["float", "null"]},
        {"name": "SPM_t0_Y", "type": ["float", "null"]},
        {"name": "IAR_phi_z", "type": ["float", "null"]},
        {"name": "Gskew_i", "type": ["float", "null"]},
        {"name": "Gskew_z", "type": ["float", "null"]},
        {"name": "max_flux_before_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_r", "type": ["float", "null"]},
        {"name": "Period_band_i", "type": ["float", "null"]},
        {"name": "Amplitude_g", "type": ["float", "null"]},
        {"name": "Mean_z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_r", "type": ["float", "null"]},
        {"name": "Pvar_u", "type": ["float", "null"]},
        {"name": "MaxSlope_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_g", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_u", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_r", "type": ["float", "null"]},
        {"name": "PPE", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_i", "type": ["float", "null"]},
        {"name": "Amplitude_z", "type": ["float", "null"]},
        {"name": "Skew_g", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_r", "type": ["float", "null"]},
        {"name": "Rcs_r", "type": ["float", "null"]},
        {"name": "mwebv", "type": ["float", "null"]},
        {"name": "MedianAbsDev_i", "type": ["float", "null"]},
        {"name": "Std_r", "type": ["float", "null"]},
        {"name": "Q31_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_z", "type": ["float", "null"]},
        {"name": "IAR_phi_i", "type": ["float", "null"]},
        {"name": "ExcessVar_r", "type": ["float", "null"]},
        {"name": "r-i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_i", "type": ["float", "null"]},
        {"name": "Q31_z", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_Y", "type": ["float", "null"]},
        {"name": "SPM_A_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_g", "type": ["float", "null"]},
        {"name": "MHPS_high_i", "type": ["float", "null"]},
        {"name": "median_flux_before_band_z", "type": ["float", "null"]},
        {"name": "max_flux_before_band_i", "type": ["float", "null"]},
        {"name": "Rcs_z", "type": ["float", "null"]},
        {"name": "Harmonics_mse_Y", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_i", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_u", "type": ["float", "null"]},
        {"name": "ExcessVar_i", "type": ["float", "null"]},
        {"name": "Gskew_g", "type": ["float", "null"]},
        {"name": "Mean_r", "type": ["float", "null"]},
        {"name": "median_flux_after_band_u", "type": ["float", "null"]},
        {"name": "SPM_A_u", "type": ["float", "null"]},
        {"name": "SPM_t0_r", "type": ["float", "null"]},
        {"name": "MHPS_low_i", "type": ["float", "null"]},
        {"name": "SPM_t0_u", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_Y", "type": ["float", "null"]},
        {"name": "StetsonK_i", "type": ["float", "null"]},
        {"name": "redshift_helio", "type": ["float", "null"]},
        {"name": "u-g", "type": ["float", "null"]},
        {"name": "LinearTrend_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_r", "type": ["float", "null"]},
        {"name": "Period_band_g", "type": ["float", "null"]},
        {"name": "Amplitude_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_i", "type": ["float", "null"]},
        {"name": "delta_period_u", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_z", "type": ["float", "null"]},
        {"name": "Power_rate_4", "type": ["float", "null"]},
        {"name": "Period_band_r", "type": ["float", "null"]},
        {"name": "Power_rate_1/2", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_r", "type": ["float", "null"]},
        {"name": "Mean_i", "type": ["float", "null"]},
        {"name": "Harmonics_mag_2_Y", "type": ["float", "null"]},
        {"name": "z-Y", "type": ["float", "null"]},
        {"name": "SPM_gamma_i", "type": ["float", "null"]},
        {"name": "last_flux_before_band_r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_z", "type": ["float", "null"]},
        {"name": "SPM_chi_i", "type": ["float", "null"]},
        {"name": "Skew_z", "type": ["float", "null"]},
        {"name": "SPM_A_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_i", "type": ["float", "null"]},
        {"name": "Beyond1Std_z", "type": ["float", "null"]},
        {"name": "Psi_eta_z", "type": ["float", "null"]},
        {"name": "SPM_chi_z", "type": ["float", "null"]},
        {"name": "Psi_eta_r", "type": ["float", "null"]},
        {"name": "Std_u", "type": ["float", "null"]},
        {"name": "Q31_r", "type": ["float", "null"]},
        {"name": "MaxSlope_Y", "type": ["float", "null"]},
        {"name": "SPM_beta_z", "type": ["float", "null"]},
        {"name": "Autocor_length_g", "type": ["float", "null"]},
        {"name": "Q31_i", "type": ["float", "null"]},
        {"name": "Beyond1Std_i", "type": ["float", "null"]},
        {"name": "median_flux_before_band_i", "type": ["float", "null"]},
        {"name": "max_flux_before_band_Y", "type": ["float", "null"]},
        {"name": "g-r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_i", "type": ["float", "null"]},
        {"name": "Std_g", "type": ["float", "null"]},
        {"name": "Power_rate_3", "type": ["float", "null"]},
        {"name": "PercentAmplitude_z", "type": ["float", "null"]},
        {"name": "SPM_chi_Y", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_g", "type": ["float", "null"]},
        {"name": "MaxSlope_r", "type": ["float", "null"]},
        {"name": "SPM_chi_g", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_2", "type": ["float", "null"]},
        {"name": "SPM_beta_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_r", "type": ["float", "null"]},
        {"name": "MedianAbsDev_g", "type": ["float", "null"]},
        {"name": "last_flux_before_band_z", "type": ["float", "null"]},
        {"name": "StetsonK_z", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_u", "type": ["float", "null"]},
        {"name": "last_flux_before_band_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_Y", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_g", "type": ["float", "null"]},
        {"name": "LinearTrend_r", "type": ["float", "null"]},
        {"name": "MHPS_low_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_z", "type": ["float", "null"]},
        {"name": "SPM_t0_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_i", "type": ["float", "null"]},
        {"name": "Std_Y", "type": ["float", "null"]},
        {"name": "positive_fraction_r", "type": ["float", "null"]},
        {"name": "Pvar_g", "type": ["float", "null"]},
        {"name": "SPM_beta_r", "type": ["float", "null"]},
        {"name": "i-z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_u", "type": ["float", "null"]},
        {"name": "SmallKurtosis_z", "type": ["float", "null"]},
        {"name": "Psi_eta_Y", "type": ["float", "null"]},
        {"name": "SPM_chi_r", "type": ["float", "null"]},
        {"name": "Rcs_i", "type": ["float", "null"]},
        {"name": "SPM_A_r", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/4", "type": ["float", "null"]},
        {"name": "Gskew_Y", "type": ["float", "null"]},
        {"name": "SPM_beta_u", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_u", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_i", "type": ["float", "null"]},
        {"name": "median_flux_after_band_Y", "type": ["float", "null"]},
        {"name": "Autocor_length_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_u", "type": ["float", "null"]},
        {"name": "SPM_A_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_Y", "type": ["float", "null"]},
        {"name": "MHPS_low_z", "type": ["float", "null"]},
        {"name": "SPM_A_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_i", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_z", "type": ["float", "null"]},
        {"name": "ExcessVar_Y", "type": ["float", "null"]},
        {"name": "Power_rate_1/3", "type": ["float", "null"]},
        {"name": "Harmonics_mse_r", "type": ["float", "null"]},
        {"name": "SPM_chi_u", "type": ["float", "null"]},
        {"name": "Amplitude_i", "type": ["float", "null"]},
        {"name": "Q31_u", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_z", "type": ["float", "null"]},
        {"name": "Std_z", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_i", "type": ["float", "null"]},
        {"name": "Skew_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_4_i", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_i", "type": ["float", "null"]},
        {"name": "IAR_phi_g", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_r", "type": ["float", "null"]},
        {"name": "Harmonics_mse_z", "type": ["float", "null"]},
        {"name": "positive_fraction_i", "type": ["float", "null"]},
        {"name": "Harmonics_mse_i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_z", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_i", "type": ["float", "null"]},
        {"name": "MedianAbsDev_u", "type": ["float", "null"]},
        {"name": "ExcessVar_z", "type": ["float", "null"]},
        {"name": "Std_i", "type": ["float", "null"]},
        {"name": "Skew_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_z", "type": ["float", "null"]},
        {"name": "Meanvariance_z", "type": ["float", "null"]},
        {"name": "median_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_Y", "type": ["float", "null"]},
        {"name": "median_flux_before_band_r", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_z", "type": ["float", "null"]},
        {"name": "SPM_gamma_z", "type": ["float", "null"]},
        {"name": "max_flux_after_band_r", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_Y", "type": ["float", "null"]},
        {"name": "AndersonDarling_r", "type": ["float", "null"]},
        {"name": "SPM_t0_i", "type": ["float", "null"]},
        {"name": "positive_fraction_z", "type": ["float", "null"]},
        {"name": "ExcessVar_g", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_r", "type": ["float", "null"]},
        {"name": "max_flux_after_band_z", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_z", "type": ["float", "null"]},
        {"name": "positive_fraction_g", "type": ["float", "null"]},
        {"name": "max_flux_before_band_z", "type": ["float", "null"]},
        {"name": "Period_band_z", "type": ["float", "null"]},
        {"name": "MHPS_high_z", "type": ["float", "null"]},
        {"name": "median_flux_after_band_g", "type": ["float", "null"]},
        {"name": "n_non_det_before_band_z", "type": ["float", "null"]},
        {"name": "StetsonK_r", "type": ["float", "null"]},
        {"name": "Gskew_u", "type": ["float", "null"]},
        {"name": "Rcs_g", "type": ["float", "null"]},
        {"name": "MedianAbsDev_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_z", "type": ["float", "null"]},
        {"name": "Eta_e_u", "type": ["float", "null"]},
        {"name": "IAR_phi_r", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_r", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_Y", "type": ["float", "null"]},
        {"name": "Q31_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_r", "type": ["float", "null"]},
        {"name": "MaxSlope_i", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_r", "type": ["float", "null"]},
        {"name": "LinearTrend_z", "type": ["float", "null"]},
        {"name": "Gskew_r", "type": ["float", "null"]},
        {"name": "SPM_t0_z", "type": ["float", "null"]},
        {"name": "Multiband_period", "type": ["float", "null"]},
        {"name": "max_flux_after_band_g", "type": ["float", "null"]},
        {"name": "Meanvariance_r", "type": ["float", "null"]},
        {"name": "MHPS_high_r", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_r", "type": ["float", "null"]},
        {"name": "median_flux_before_band_Y", "type": ["float", "null"]},
        {"name": "Pvar_Y", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_g", "type": ["float", "null"]},
        {"name": "AndersonDarling_i", "type": ["float", "null"]},
        {"name": "SPM_gamma_g", "type": ["float", "null"]},
        {"name": "Period_band_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_Y", "type": ["float", "null"]},
        {"name": "Skew_Y", "type": ["float", "null"]},
        {"name": "SPM_gamma_r", "type": ["float", "null"]},
        {"name": "SPM_t0_Y", "type": ["float", "null"]},
        {"name": "IAR_phi_z", "type": ["float", "null"]},
        {"name": "Gskew_i", "type": ["float", "null"]},
        {"name": "Gskew_z", "type": ["float", "null"]},
        {"name": "SPM_beta_g", "type": ["float", "null"]},
        {"name": "max_flux_before_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_r", "type": ["float", "null"]},
        {"name": "Period_band_i", "type": ["float", "null"]},
        {"name": "Amplitude_g", "type": ["float", "null"]},
        {"name": "Mean_z", "type": ["float", "null"]},
        {"name": "GP_DRW_sigma_r", "type": ["float", "null"]},
        {"name": "Pvar_u", "type": ["float", "null"]},
        {"name": "MaxSlope_g", "type": ["float", "null"]},
        {"name": "SPM_tau_rise_g", "type": ["float", "null"]},
        {"name": "Psi_CS_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_r", "type": ["float", "null"]},
        {"name": "Amplitude_u", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_r", "type": ["float", "null"]},
        {"name": "PPE", "type": ["float", "null"]},
        {"name": "GP_DRW_tau_i", "type": ["float", "null"]},
        {"name": "Amplitude_z", "type": ["float", "null"]},
        {"name": "Skew_g", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_i", "type": ["float", "null"]},
        {"name": "dflux_first_det_band_r", "type": ["float", "null"]},
        {"name": "Rcs_r", "type": ["float", "null"]},
        {"name": "mwebv", "type": ["float", "null"]},
        {"name": "MedianAbsDev_i", "type": ["float", "null"]},
        {"name": "Std_r", "type": ["float", "null"]},
        {"name": "Q31_g", "type": ["float", "null"]},
        {"name": "Harmonics_phase_2_z", "type": ["float", "null"]},
        {"name": "IAR_phi_i", "type": ["float", "null"]},
        {"name": "ExcessVar_r", "type": ["float", "null"]},
        {"name": "SPM_gamma_Y", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_i", "type": ["float", "null"]},
        {"name": "r-i", "type": ["float", "null"]},
        {"name": "n_non_det_after_band_i", "type": ["float", "null"]},
        {"name": "Q31_z", "type": ["float", "null"]},
        {"name": "Harmonics_phase_3_Y", "type": ["float", "null"]},
        {"name": "SPM_A_z", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_g", "type": ["float", "null"]},
        {"name": "MHPS_high_i", "type": ["float", "null"]},
        {"name": "median_flux_before_band_z", "type": ["float", "null"]},
        {"name": "max_flux_before_band_i", "type": ["float", "null"]},
        {"name": "Rcs_z", "type": ["float", "null"]},
        {"name": "Harmonics_mse_Y", "type": ["float", "null"]},
        {"name": "SPM_beta_i", "type": ["float", "null"]},
        {"name": "Psi_CS_r", "type": ["float", "null"]},
        {"name": "Psi_CS_i", "type": ["float", "null"]},
        {"name": "dflux_non_det_band_i", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_u", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_z", "type": ["float", "null"]},
        {"name": "ExcessVar_i", "type": ["float", "null"]},
        {"name": "Gskew_g", "type": ["float", "null"]},
        {"name": "Mean_r", "type": ["float", "null"]},
        {"name": "median_flux_after_band_u", "type": ["float", "null"]},
        {"name": "last_flux_before_band_Y", "type": ["float", "null"]},
        {"name": "SPM_A_u", "type": ["float", "null"]},
        {"name": "SPM_t0_r", "type": ["float", "null"]},
        {"name": "MHPS_low_i", "type": ["float", "null"]},
        {"name": "SPM_t0_u", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_Y", "type": ["float", "null"]},
        {"name": "StetsonK_i", "type": ["float", "null"]},
        {"name": "redshift_helio", "type": ["float", "null"]},
        {"name": "Psi_eta_i", "type": ["float", "null"]},
        {"name": "u-g", "type": ["float", "null"]},
        {"name": "LinearTrend_g", "type": ["float", "null"]},
        {"name": "median_flux_after_band_r", "type": ["float", "null"]},
        {"name": "Period_band_g", "type": ["float", "null"]},
        {"name": "Amplitude_Y", "type": ["float", "null"]},
        {"name": "Harmonics_phase_5_i", "type": ["float", "null"]},
        {"name": "delta_period_u", "type": ["float", "null"]},
        {"name": "Harmonics_mag_1_z", "type": ["float", "null"]},
        {"name": "SPM_tau_fall_Y", "type": ["float", "null"]},
    ],
}

INPUT_SCHEMA = {
    "doc": "Multi stream light curve with xmatch",
    "name": "alerce.light_curve_xmatched",
    "type": "record",
    "fields": [
        {"name": "aid", "type": "string"},
        {"name": "meanra", "type": "float"},
        {"name": "meandec", "type": "float"},
        {"name": "detections", "type": DETECTIONS},
        {"name": "non_detections", "type": NON_DETECTIONS},
        {"name": "xmatches", "type": [XMATCH, "null"]},
        {"name": "features", "type": [FEATURES_SCHEMA, "null"]},
    ],
}
