FROM python:3.7
ARG GITHUB_TOKEN

#Model installation
COPY model.zip /app/model.zip
RUN unzip /app/model.zip -d /app/model
RUN pip install -r /app/model/requirements.txt

# Code installation
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

WORKDIR /app
COPY . /app

WORKDIR /app/scripts

CMD ["python", "run_step.py"]