##################################################
#       features   Settings File
##################################################
import os

FEATURE_VERSION = os.environ["FEATURE_VERSION"]
STEP_VERSION = os.environ["STEP_VERSION"]

DB_CONFIG = {
    "SQL": {
        "ENGINE": os.environ["DB_ENGINE"],
        "HOST": os.environ["DB_HOST"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "PORT": int(os.environ["DB_PORT"]),
        "DB_NAME": os.environ["DB_NAME"],
    }
}

CONSUMER_CONFIG = {
    "TOPICS": os.environ["CONSUMER_TOPICS"].strip().split(","),
    "PARAMS": {
        "bootstrap.servers": os.environ["CONSUMER_SERVER"],
        "group.id": os.environ["CONSUMER_GROUP_ID"],
    },
}

PRODUCER_CONFIG = {
    "TOPIC": os.environ["PRODUCER_TOPIC"],
    "PARAMS": {
        "bootstrap.servers": os.environ["PRODUCER_SERVER"],
    },
    "SCHEMA": {
        "doc": "Features",
        "name": "features",
        "type": "record",
        "fields": [
            {"name": "oid", "type": "string"},
            {"name": "candid", "type": "long"},
            {
                "name": "features_field",
                "type": {
                    "name": "features_record",
                    "type": "record",
                    "fields": [
                        {"name": "Amplitude_1", "type": "float"},
                        {"name": "Amplitude_2", "type": "float"},
                        {"name": "AndersonDarling_1", "type": "float"},
                        {"name": "AndersonDarling_2", "type": "float"},
                        {"name": "Autocor_length_1", "type": "double"},
                        {"name": "Autocor_length_2", "type": "double"},
                        {"name": "Beyond1Std_1", "type": "float"},
                        {"name": "Beyond1Std_2", "type": "float"},
                        {"name": "Con_1", "type": "double"},
                        {"name": "Con_2", "type": "double"},
                        {"name": "Eta_e_1", "type": "float"},
                        {"name": "Eta_e_2", "type": "float"},
                        {"name": "ExcessVar_1", "type": "double"},
                        {"name": "ExcessVar_2", "type": "double"},
                        {"name": "GP_DRW_sigma_1", "type": "double"},
                        {"name": "GP_DRW_sigma_2", "type": "double"},
                        {"name": "GP_DRW_tau_1", "type": "float"},
                        {"name": "GP_DRW_tau_2", "type": "float"},
                        {"name": "Gskew_1", "type": "float"},
                        {"name": "Gskew_2", "type": "float"},
                        {"name": "Harmonics_mag_1_1", "type": "float"},
                        {"name": "Harmonics_mag_1_2", "type": "float"},
                        {"name": "Harmonics_mag_2_1", "type": "float"},
                        {"name": "Harmonics_mag_2_2", "type": "float"},
                        {"name": "Harmonics_mag_3_1", "type": "float"},
                        {"name": "Harmonics_mag_3_2", "type": "float"},
                        {"name": "Harmonics_mag_4_1", "type": "float"},
                        {"name": "Harmonics_mag_4_2", "type": "float"},
                        {"name": "Harmonics_mag_5_1", "type": "float"},
                        {"name": "Harmonics_mag_5_2", "type": "float"},
                        {"name": "Harmonics_mag_6_1", "type": "float"},
                        {"name": "Harmonics_mag_6_2", "type": "float"},
                        {"name": "Harmonics_mag_7_1", "type": "float"},
                        {"name": "Harmonics_mag_7_2", "type": "float"},
                        {"name": "Harmonics_mse_1", "type": "double"},
                        {"name": "Harmonics_mse_2", "type": "double"},
                        {"name": "Harmonics_phase_2_1", "type": "float"},
                        {"name": "Harmonics_phase_2_2", "type": "float"},
                        {"name": "Harmonics_phase_3_1", "type": "float"},
                        {"name": "Harmonics_phase_3_2", "type": "float"},
                        {"name": "Harmonics_phase_4_1", "type": "float"},
                        {"name": "Harmonics_phase_4_2", "type": "float"},
                        {"name": "Harmonics_phase_5_1", "type": "float"},
                        {"name": "Harmonics_phase_5_2", "type": "float"},
                        {"name": "Harmonics_phase_6_1", "type": "float"},
                        {"name": "Harmonics_phase_6_2", "type": "float"},
                        {"name": "Harmonics_phase_7_1", "type": "float"},
                        {"name": "Harmonics_phase_7_2", "type": "float"},
                        {"name": "IAR_phi_1", "type": "double"},
                        {"name": "IAR_phi_2", "type": "float"},
                        {"name": "LinearTrend_1", "type": "float"},
                        {"name": "LinearTrend_2", "type": "double"},
                        {"name": "MHPS_PN_flag_1", "type": "double"},
                        {"name": "MHPS_PN_flag_2", "type": "double"},
                        {"name": "MHPS_high_1", "type": "float"},
                        {"name": "MHPS_high_2", "type": "double"},
                        {"name": "MHPS_low_1", "type": "float"},
                        {"name": "MHPS_low_2", "type": "float"},
                        {"name": "MHPS_non_zero_1", "type": "double"},
                        {"name": "MHPS_non_zero_2", "type": "double"},
                        {"name": "MHPS_ratio_1", "type": "float"},
                        {"name": "MHPS_ratio_2", "type": "float"},
                        {"name": "MaxSlope_1", "type": "float"},
                        {"name": "MaxSlope_2", "type": "float"},
                        {"name": "Mean_1", "type": "float"},
                        {"name": "Mean_2", "type": "float"},
                        {"name": "Meanvariance_1", "type": "float"},
                        {"name": "Meanvariance_2", "type": "float"},
                        {"name": "MedianAbsDev_1", "type": "float"},
                        {"name": "MedianAbsDev_2", "type": "float"},
                        {"name": "MedianBRP_1", "type": "float"},
                        {"name": "MedianBRP_2", "type": "float"},
                        {"name": "Multiband_period", "type": "float"},
                        {"name": "PairSlopeTrend_1", "type": "float"},
                        {"name": "PairSlopeTrend_2", "type": "float"},
                        {"name": "PercentAmplitude_1", "type": "float"},
                        {"name": "PercentAmplitude_2", "type": "float"},
                        {"name": "Period_band_1", "type": "float"},
                        {"name": "Period_band_2", "type": "float"},
                        {"name": "Period_fit", "type": "float"},
                        {"name": "Power_rate_1/2", "type": "float"},
                        {"name": "Power_rate_1/3", "type": "float"},
                        {"name": "Power_rate_1/4", "type": "float"},
                        {"name": "Power_rate_2", "type": "float"},
                        {"name": "Power_rate_3", "type": "float"},
                        {"name": "Power_rate_4", "type": "float"},
                        {"name": "Psi_CS_1", "type": "float"},
                        {"name": "Psi_CS_2", "type": "float"},
                        {"name": "Psi_eta_1", "type": "float"},
                        {"name": "Psi_eta_2", "type": "float"},
                        {"name": "Pvar_1", "type": "float"},
                        {"name": "Pvar_2", "type": "float"},
                        {"name": "Q31_1", "type": "float"},
                        {"name": "Q31_2", "type": "float"},
                        {"name": "Rcs_1", "type": "float"},
                        {"name": "Rcs_2", "type": "float"},
                        {"name": "SF_ML_amplitude_1", "type": "float"},
                        {"name": "SF_ML_amplitude_2", "type": "float"},
                        {"name": "SF_ML_gamma_1", "type": "float"},
                        {"name": "SF_ML_gamma_2", "type": "float"},
                        {"name": "SPM_A_1", "type": "float"},
                        {"name": "SPM_A_2", "type": "float"},
                        {"name": "SPM_beta_1", "type": "float"},
                        {"name": "SPM_beta_2", "type": "float"},
                        {"name": "SPM_chi_1", "type": "float"},
                        {"name": "SPM_chi_2", "type": "float"},
                        {"name": "SPM_gamma_1", "type": "float"},
                        {"name": "SPM_gamma_2", "type": "float"},
                        {"name": "SPM_t0_1", "type": "float"},
                        {"name": "SPM_t0_2", "type": "float"},
                        {"name": "SPM_tau_fall_1", "type": "float"},
                        {"name": "SPM_tau_fall_2", "type": "float"},
                        {"name": "SPM_tau_rise_1", "type": "float"},
                        {"name": "SPM_tau_rise_2", "type": "float"},
                        {"name": "Skew_1", "type": "float"},
                        {"name": "Skew_2", "type": "float"},
                        {"name": "SmallKurtosis_1", "type": "float"},
                        {"name": "SmallKurtosis_2", "type": "float"},
                        {"name": "Std_1", "type": "float"},
                        {"name": "Std_2", "type": "float"},
                        {"name": "StetsonK_1", "type": "float"},
                        {"name": "StetsonK_2", "type": "float"},
                        {"name": "W1-W2", "type": ["string", "null"]},
                        {"name": "W2-W3", "type": ["string", "null"]},
                        {"name": "delta_mag_fid_1", "type": "float"},
                        {"name": "delta_mag_fid_2", "type": "float"},
                        {"name": "delta_mjd_fid_1", "type": "float"},
                        {"name": "delta_mjd_fid_2", "type": "float"},
                        {"name": "dmag_first_det_fid_1", "type": ["string", "null"]},
                        {"name": "dmag_first_det_fid_2", "type": ["string", "null"]},
                        {"name": "dmag_non_det_fid_1", "type": ["string", "null"]},
                        {"name": "dmag_non_det_fid_2", "type": ["string", "null"]},
                        {"name": "first_mag_1", "type": "float"},
                        {"name": "first_mag_2", "type": "float"},
                        {"name": "g-W2", "type": ["string", "null"]},
                        {"name": "g-W3", "type": ["string", "null"]},
                        {"name": "g-r_max", "type": "float"},
                        {"name": "g-r_max_corr", "type": "float"},
                        {"name": "g-r_mean", "type": "float"},
                        {"name": "g-r_mean_corr", "type": "float"},
                        {"name": "gal_b", "type": "float"},
                        {"name": "gal_l", "type": "float"},
                        {"name": "iqr_1", "type": "float"},
                        {"name": "iqr_2", "type": "float"},
                        {
                            "name": "last_diffmaglim_before_fid_1",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "last_diffmaglim_before_fid_2",
                            "type": ["string", "null"],
                        },
                        {"name": "last_mjd_before_fid_1", "type": ["string", "null"]},
                        {"name": "last_mjd_before_fid_2", "type": ["string", "null"]},
                        {
                            "name": "max_diffmaglim_after_fid_1",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "max_diffmaglim_after_fid_2",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "max_diffmaglim_before_fid_1",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "max_diffmaglim_before_fid_2",
                            "type": ["string", "null"],
                        },
                        {"name": "mean_mag_1", "type": "float"},
                        {"name": "mean_mag_2", "type": "float"},
                        {
                            "name": "median_diffmaglim_after_fid_1",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "median_diffmaglim_after_fid_2",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "median_diffmaglim_before_fid_1",
                            "type": ["string", "null"],
                        },
                        {
                            "name": "median_diffmaglim_before_fid_2",
                            "type": ["string", "null"],
                        },
                        {"name": "min_mag_1", "type": "float"},
                        {"name": "min_mag_2", "type": "float"},
                        {"name": "n_det_1", "type": "double"},
                        {"name": "n_det_2", "type": "double"},
                        {"name": "n_neg_1", "type": "double"},
                        {"name": "n_neg_2", "type": "double"},
                        {"name": "n_non_det_after_fid_1", "type": "double"},
                        {"name": "n_non_det_after_fid_2", "type": "double"},
                        {"name": "n_non_det_before_fid_1", "type": "double"},
                        {"name": "n_non_det_before_fid_2", "type": "double"},
                        {"name": "n_pos_1", "type": "double"},
                        {"name": "n_pos_2", "type": "double"},
                        {"name": "positive_fraction_1", "type": "double"},
                        {"name": "positive_fraction_2", "type": "double"},
                        {"name": "r-W2", "type": ["string", "null"]},
                        {"name": "r-W3", "type": ["string", "null"]},
                        {"name": "rb", "type": "float"},
                        {"name": "sgscore1", "type": "float"},
                    ],
                },
            },
        ],
    },
}

# ES_CONFIG = {
#    "INDEX_PREFIX": os.environ["ES_PREFIX"],
#    "host": os.environ["ES_NETWORK_HOST"],
#    "port": os.environ["ES_NETWORK_PORT"]
# }

STEP_CONFIG = {
    "CONSUMER_CONFIG": CONSUMER_CONFIG,
    "DB_CONFIG": DB_CONFIG,
    # "ES_CONFIG": ES_CONFIG,
    "PRODUCER_CONFIG": PRODUCER_CONFIG,
    "FEATURE_VERSION": FEATURE_VERSION,
    "STEP_VERSION": STEP_VERSION,
    "STEP_VERSION_PREPROCESS": "v1",
}
