from typing import Any, TypedDict


class InitData(TypedDict):
    index_elements: list[str]
    data: list[dict[str, Any]]


INITIAL_DATA: dict[str, InitData] = {
    "classifier": {
        "index_elements": ["classifier_id"],
        "data": [
            {
                "classifier_id": 1,
                "classifier_name": "stamp_classifier_rubin",
                "classifier_version": "2.0.1",
                "tid": 1,
            },
            {
                "classifier_id": 2,
                "classifier_name": "stamp_classifier_2025_beta",
                "classifier_version": "2.1.1",
                "tid": 0,
            },
        ],
    },
    "feature_name_lut": {
        "index_elements": ["feature_id"],
        "data": [
            {"feature_id": 0, "feature_name": "u-g_mean", "sid": 1, "tid": 1},
            {"feature_id": 1, "feature_name": "u-g_max", "sid": 1, "tid": 1},
            {"feature_id": 2, "feature_name": "g-r_mean", "sid": 1, "tid": 1},
            {"feature_id": 3, "feature_name": "g-r_max", "sid": 1, "tid": 1},
            {"feature_id": 4, "feature_name": "r-i_mean", "sid": 1, "tid": 1},
            {"feature_id": 5, "feature_name": "r-i_max", "sid": 1, "tid": 1},
            {"feature_id": 6, "feature_name": "i-z_mean", "sid": 1, "tid": 1},
            {"feature_id": 7, "feature_name": "i-z_max", "sid": 1, "tid": 1},
            {"feature_id": 8, "feature_name": "z-y_mean", "sid": 1, "tid": 1},
            {"feature_id": 9, "feature_name": "z-y_max", "sid": 1, "tid": 1},
            {"feature_id": 10, "feature_name": "u-g_mean_corr", "sid": 1, "tid": 1},
            {"feature_id": 11, "feature_name": "u-g_max_corr", "sid": 1, "tid": 1},
            {"feature_id": 12, "feature_name": "g-r_mean_corr", "sid": 1, "tid": 1},
            {"feature_id": 13, "feature_name": "g-r_max_corr", "sid": 1, "tid": 1},
            {"feature_id": 14, "feature_name": "r-i_mean_corr", "sid": 1, "tid": 1},
            {"feature_id": 15, "feature_name": "r-i_max_corr", "sid": 1, "tid": 1},
            {"feature_id": 16, "feature_name": "i-z_mean_corr", "sid": 1, "tid": 1},
            {"feature_id": 17, "feature_name": "i-z_max_corr", "sid": 1, "tid": 1},
            {"feature_id": 18, "feature_name": "z-y_mean_corr", "sid": 1, "tid": 1},
            {"feature_id": 19, "feature_name": "z-y_max_corr", "sid": 1, "tid": 1},
            {"feature_id": 20, "feature_name": "Timespan", "sid": 1, "tid": 1},
            {"feature_id": 21, "feature_name": "Coordinate_x", "sid": 1, "tid": 1},
            {"feature_id": 22, "feature_name": "Coordinate_y", "sid": 1, "tid": 1},
            {"feature_id": 23, "feature_name": "Coordinate_z", "sid": 1, "tid": 1},
            {"feature_id": 24, "feature_name": "TDE_decay", "sid": 1, "tid": 1},
            {"feature_id": 25, "feature_name": "TDE_decay_chi", "sid": 1, "tid": 1},
            {"feature_id": 26, "feature_name": "TDE_mag0", "sid": 1, "tid": 1},
            {"feature_id": 27, "feature_name": "Multiband_period", "sid": 1, "tid": 1},
            {"feature_id": 28, "feature_name": "PPE", "sid": 1, "tid": 1},
            {"feature_id": 29, "feature_name": "Period_band", "sid": 1, "tid": 1},
            {"feature_id": 30, "feature_name": "delta_period", "sid": 1, "tid": 1},
            {"feature_id": 31, "feature_name": "Power_rate_1/4", "sid": 1, "tid": 1},
            {"feature_id": 32, "feature_name": "Power_rate_1/3", "sid": 1, "tid": 1},
            {"feature_id": 33, "feature_name": "Power_rate_1/2", "sid": 1, "tid": 1},
            {"feature_id": 34, "feature_name": "Power_rate_2", "sid": 1, "tid": 1},
            {"feature_id": 35, "feature_name": "Power_rate_3", "sid": 1, "tid": 1},
            {"feature_id": 36, "feature_name": "Power_rate_4", "sid": 1, "tid": 1},
            {"feature_id": 37, "feature_name": "MHPS_ratio", "sid": 1, "tid": 1},
            {"feature_id": 38, "feature_name": "MHPS_low", "sid": 1, "tid": 1},
            {"feature_id": 39, "feature_name": "MHPS_high", "sid": 1, "tid": 1},
            {"feature_id": 40, "feature_name": "MHPS_non_zero", "sid": 1, "tid": 1},
            {"feature_id": 41, "feature_name": "MHPS_PN_flag", "sid": 1, "tid": 1},
            {"feature_id": 42, "feature_name": "MHPS_ratio_365_30", "sid": 1, "tid": 1},
            {"feature_id": 43, "feature_name": "MHPS_low_365", "sid": 1, "tid": 1},
            {"feature_id": 44, "feature_name": "MHPS_high_30", "sid": 1, "tid": 1},
            {"feature_id": 45, "feature_name": "GP_DRW_sigma", "sid": 1, "tid": 1},
            {"feature_id": 46, "feature_name": "GP_DRW_tau", "sid": 1, "tid": 1},
            {"feature_id": 47, "feature_name": "Psi_CS", "sid": 1, "tid": 1},
            {"feature_id": 48, "feature_name": "Psi_eta", "sid": 1, "tid": 1},
            {"feature_id": 49, "feature_name": "Harmonics_mse", "sid": 1, "tid": 1},
            {"feature_id": 50, "feature_name": "Harmonics_chi", "sid": 1, "tid": 1},
            {"feature_id": 51, "feature_name": "Harmonics_mag_1", "sid": 1, "tid": 1},
            {"feature_id": 52, "feature_name": "Harmonics_mag_2", "sid": 1, "tid": 1},
            {"feature_id": 53, "feature_name": "Harmonics_phase_2", "sid": 1, "tid": 1},
            {"feature_id": 54, "feature_name": "Harmonics_mag_3", "sid": 1, "tid": 1},
            {"feature_id": 55, "feature_name": "Harmonics_phase_3", "sid": 1, "tid": 1},
            {"feature_id": 56, "feature_name": "Harmonics_mag_4", "sid": 1, "tid": 1},
            {"feature_id": 57, "feature_name": "Harmonics_phase_4", "sid": 1, "tid": 1},
            {"feature_id": 58, "feature_name": "Harmonics_mag_5", "sid": 1, "tid": 1},
            {"feature_id": 59, "feature_name": "Harmonics_phase_5", "sid": 1, "tid": 1},
            {"feature_id": 60, "feature_name": "Harmonics_mag_6", "sid": 1, "tid": 1},
            {"feature_id": 61, "feature_name": "Harmonics_phase_6", "sid": 1, "tid": 1},
            {"feature_id": 62, "feature_name": "Harmonics_mag_7", "sid": 1, "tid": 1},
            {"feature_id": 63, "feature_name": "Harmonics_phase_7", "sid": 1, "tid": 1},
            {"feature_id": 64, "feature_name": "Amplitude", "sid": 1, "tid": 1},
            {"feature_id": 65, "feature_name": "AndersonDarling", "sid": 1, "tid": 1},
            {"feature_id": 66, "feature_name": "Autocor_length", "sid": 1, "tid": 1},
            {"feature_id": 67, "feature_name": "Beyond1Std", "sid": 1, "tid": 1},
            {"feature_id": 68, "feature_name": "Con", "sid": 1, "tid": 1},
            {"feature_id": 69, "feature_name": "Eta_e", "sid": 1, "tid": 1},
            {"feature_id": 70, "feature_name": "Gskew", "sid": 1, "tid": 1},
            {"feature_id": 71, "feature_name": "MaxSlope", "sid": 1, "tid": 1},
            {"feature_id": 72, "feature_name": "Mean", "sid": 1, "tid": 1},
            {"feature_id": 73, "feature_name": "Meanvariance", "sid": 1, "tid": 1},
            {"feature_id": 74, "feature_name": "MedianAbsDev", "sid": 1, "tid": 1},
            {"feature_id": 75, "feature_name": "MedianBRP", "sid": 1, "tid": 1},
            {"feature_id": 76, "feature_name": "PairSlopeTrend", "sid": 1, "tid": 1},
            {"feature_id": 77, "feature_name": "PercentAmplitude", "sid": 1, "tid": 1},
            {"feature_id": 78, "feature_name": "Q31", "sid": 1, "tid": 1},
            {"feature_id": 79, "feature_name": "Rcs", "sid": 1, "tid": 1},
            {"feature_id": 80, "feature_name": "Skew", "sid": 1, "tid": 1},
            {"feature_id": 81, "feature_name": "SmallKurtosis", "sid": 1, "tid": 1},
            {"feature_id": 82, "feature_name": "Std", "sid": 1, "tid": 1},
            {"feature_id": 83, "feature_name": "StetsonK", "sid": 1, "tid": 1},
            {"feature_id": 84, "feature_name": "Pvar", "sid": 1, "tid": 1},
            {"feature_id": 85, "feature_name": "ExcessVar", "sid": 1, "tid": 1},
            {"feature_id": 86, "feature_name": "SF_ML_amplitude", "sid": 1, "tid": 1},
            {"feature_id": 87, "feature_name": "SF_ML_gamma", "sid": 1, "tid": 1},
            {"feature_id": 88, "feature_name": "IAR_phi", "sid": 1, "tid": 1},
            {"feature_id": 89, "feature_name": "LinearTrend", "sid": 1, "tid": 1},
            {"feature_id": 90, "feature_name": "SPM_A", "sid": 1, "tid": 1},
            {"feature_id": 91, "feature_name": "SPM_t0", "sid": 1, "tid": 1},
            {"feature_id": 92, "feature_name": "SPM_gamma", "sid": 1, "tid": 1},
            {"feature_id": 93, "feature_name": "SPM_beta", "sid": 1, "tid": 1},
            {"feature_id": 94, "feature_name": "SPM_tau_rise", "sid": 1, "tid": 1},
            {"feature_id": 95, "feature_name": "SPM_tau_fall", "sid": 1, "tid": 1},
            {"feature_id": 96, "feature_name": "SPM_chi", "sid": 1, "tid": 1},
            {"feature_id": 97, "feature_name": "fleet_a", "sid": 1, "tid": 1},
            {"feature_id": 98, "feature_name": "fleet_w", "sid": 1, "tid": 1},
            {"feature_id": 99, "feature_name": "fleet_chi", "sid": 1, "tid": 1},
            {"feature_id": 100, "feature_name": "fleet_m0", "sid": 1, "tid": 1},
            {"feature_id": 101, "feature_name": "fleet_t0", "sid": 1, "tid": 1},
            {"feature_id": 102, "feature_name": "color_variation", "sid": 1, "tid": 1},
            {"feature_id": 103, "feature_name": "positive_fraction", "sid": 1, "tid": 1},
            {"feature_id": 104, "feature_name": "n_forced_phot_band_before", "sid": 1, "tid": 1},
            {"feature_id": 105, "feature_name": "dbrightness_first_det_band", "sid": 1, "tid": 1},
            {"feature_id": 106, "feature_name": "dbrightness_forced_phot_band", "sid": 1, "tid": 1},
            {"feature_id": 107, "feature_name": "last_brightness_before_band", "sid": 1, "tid": 1},
            {"feature_id": 108, "feature_name": "max_brightness_before_band", "sid": 1, "tid": 1},
            {"feature_id": 109, "feature_name": "median_brightness_before_band", "sid": 1, "tid": 1},
            {"feature_id": 110, "feature_name": "n_forced_phot_band_after", "sid": 1, "tid": 1},
            {"feature_id": 111, "feature_name": "max_brightness_after_band", "sid": 1, "tid": 1},
            {"feature_id": 112, "feature_name": "median_brightness_after_band", "sid": 1, "tid": 1},
            {"feature_id": 113, "feature_name": "ulens_u0", "sid": 1, "tid": 1},
            {"feature_id": 114, "feature_name": "ulens_tE", "sid": 1, "tid": 1},
            {"feature_id": 115, "feature_name": "ulens_fs", "sid": 1, "tid": 1},
            {"feature_id": 116, "feature_name": "ulens_chi", "sid": 1, "tid": 1},
            {"feature_id": 117, "feature_name": "ulens_t0", "sid": 1, "tid": 1},
            {"feature_id": 118, "feature_name": "ulens_mag0", "sid": 1, "tid": 1},
            {"feature_id": 119, "feature_name": "W1-W2", "sid": 1, "tid": 1},
            {"feature_id": 120, "feature_name": "W2-W3", "sid": 1, "tid": 1},
            {"feature_id": 121, "feature_name": "W3-W4", "sid": 1, "tid": 1},
            {"feature_id": 122, "feature_name": "u-W1", "sid": 1, "tid": 1},
            {"feature_id": 123, "feature_name": "u-W2", "sid": 1, "tid": 1},
            {"feature_id": 124, "feature_name": "u-W3", "sid": 1, "tid": 1},
            {"feature_id": 125, "feature_name": "u-W4", "sid": 1, "tid": 1},
            {"feature_id": 126, "feature_name": "g-W1", "sid": 1, "tid": 1},
            {"feature_id": 127, "feature_name": "g-W2", "sid": 1, "tid": 1},
            {"feature_id": 128, "feature_name": "g-W3", "sid": 1, "tid": 1},
            {"feature_id": 129, "feature_name": "g-W4", "sid": 1, "tid": 1},
            {"feature_id": 130, "feature_name": "r-W1", "sid": 1, "tid": 1},
            {"feature_id": 131, "feature_name": "r-W2", "sid": 1, "tid": 1},
            {"feature_id": 132, "feature_name": "r-W3", "sid": 1, "tid": 1},
            {"feature_id": 133, "feature_name": "r-W4", "sid": 1, "tid": 1},
            {"feature_id": 134, "feature_name": "i-W1", "sid": 1, "tid": 1},
            {"feature_id": 135, "feature_name": "i-W2", "sid": 1, "tid": 1},
            {"feature_id": 136, "feature_name": "i-W3", "sid": 1, "tid": 1},
            {"feature_id": 137, "feature_name": "i-W4", "sid": 1, "tid": 1},
            {"feature_id": 138, "feature_name": "z-W1", "sid": 1, "tid": 1},
            {"feature_id": 139, "feature_name": "z-W2", "sid": 1, "tid": 1},
            {"feature_id": 140, "feature_name": "z-W3", "sid": 1, "tid": 1},
            {"feature_id": 141, "feature_name": "z-W4", "sid": 1, "tid": 1},
            {"feature_id": 142, "feature_name": "y-W1", "sid": 1, "tid": 1},
            {"feature_id": 143, "feature_name": "y-W2", "sid": 1, "tid": 1},
            {"feature_id": 144, "feature_name": "y-W3", "sid": 1, "tid": 1},
            {"feature_id": 145, "feature_name": "y-W4", "sid": 1, "tid": 1}
        ]
    },
    "sid_lut": {
        "index_elements": ["sid"],
        "data": [
            {"sid": 0, "tid": 0, "survey_name": "ZTF"},
            {"sid": 1, "tid": 1, "survey_name": "LSST DIA Object"},
            {"sid": 2, "tid": 1, "survey_name": "LSST SS Object"},
        ],
    },
    "taxonomy": {
        "index_elements": ["class_id"],
        "data": [
            {
                "class_id": 0,
                "class_name": "SN",
                "order": 0,
                "classifier_id": 1,
            },
            {
                "class_id": 1,
                "class_name": "AGN",
                "order": 1,
                "classifier_id": 1,
            },
            {
                "class_id": 2,
                "class_name": "VS",
                "order": 2,
                "classifier_id": 1,
            },
            {
                "class_id": 3,
                "class_name": "asteroid",
                "order": 3,
                "classifier_id": 1,
            },
            {
                "class_id": 4,
                "class_name": "bogus",
                "order": 4,
                "classifier_id": 1,
            },
            {
                "class_id": 5,
                "class_name": "SN",
                "order": 0,
                "classifier_id": 2,
            },
            {
                "class_id": 6,
                "class_name": "AGN",
                "order": 1,
                "classifier_id": 2,
            },
            {
                "class_id": 7,
                "class_name": "VS",
                "order": 2,
                "classifier_id": 2,
            },
            {
                "class_id": 8,
                "class_name": "asteroid",
                "order": 3,
                "classifier_id": 2,
            },
            {
                "class_id": 9,
                "class_name": "bogus",
                "order": 4,
                "classifier_id": 2,
            },
            {
                "class_id": 10,
                "class_name": "satellite",
                "order": 5,
                "classifier_id": 2,
            },
        ],
    },
    "catalog_id_lut": {
        "index_elements": ["catid"],
        "data": [
            {"catid": 0, "catalog_name": "AllWISE"},
        ],
    },
    "band": {
        "index_elements": ["sid", "tid", "band"],
        "data": [
            {"sid": 1, "tid": 1, "band": 1, "band_name": "g", "order": 1},
            {"sid": 1, "tid": 1, "band": 2, "band_name": "r", "order": 2},
            {"sid": 1, "tid": 1, "band": 3, "band_name": "i", "order": 3},
            {"sid": 1, "tid": 1, "band": 4, "band_name": "z", "order": 4},
            {"sid": 1, "tid": 1, "band": 5, "band_name": "y", "order": 5},
            {"sid": 1, "tid": 1, "band": 6, "band_name": "u", "order": 0},
            {"sid": 2, "tid": 1, "band": 1, "band_name": "g", "order": 1},
            {"sid": 2, "tid": 1, "band": 2, "band_name": "r", "order": 2},
            {"sid": 2, "tid": 1, "band": 3, "band_name": "i", "order": 3},
            {"sid": 2, "tid": 1, "band": 4, "band_name": "z", "order": 4},
            {"sid": 2, "tid": 1, "band": 5, "band_name": "y", "order": 5},
            {"sid": 2, "tid": 1, "band": 6, "band_name": "u", "order": 0},
            {"sid": 0, "tid": 0, "band": 1, "band_name": "g", "order": 0},
            {"sid": 0, "tid": 0, "band": 2, "band_name": "r", "order": 1},
            {"sid": 0, "tid": 0, "band": 3, "band_name": "i", "order": 2},
        ],
    },
}
