# Default values for step_starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: correction-step

image:
  repository: ghcr.io/alercebroker/correction_step
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: "image-pull-access"
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  requests:
    memory: 600M
    cpu: "1"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              ## Override this value with the NodeGroup tag accordingly
              values: []

imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""

envVariables:
  - name: CONFIG_FROM_YAML
    value: "yes"
  # - name: METRICS_SOURCE
  #   value: ""
  # - name: METRICS_SURVEY
  #   value: LSST

configYaml:
  enabled: true
  CONSUMER_CONFIG:
    CLASS: "apf.consumers.KafkaConsumer"
    PARAMS:
      bootstrap.servers: ""
      group.id: "correction-step"
      auto.offset.reset: "beginning"
      enable.partition.eof: false
      security.protocol: "SASL_SSL"
      sasl.mechanisms: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPICS: ["lightcurve"]
    consume.messages: 100
    consume.timeout: 10
  METRICS_CONFIG:
    CLASS: "apf.metrics.KafkaMetricsProducer"
    EXTRA_METRICS:
      - key: aid
      - key: candid
    PARAMS:
      PARAMS:
        bootstrap.servers: ""
        security.protocol: "SASL_SSL"
        sasl.mechanisms: "SCRAM-SHA-512"
        sasl.username: ""
        sasl.password: ""
      TOPIC: "metrics"
      SCHEMA_PATH: "/schemas/correction_step/metrics.json"
  PRODUCER_CONFIG:
    CLASS: "apf.producers.KafkaProducer"
    PARAMS:
      bootstrap.servers: ""
      security.protocol: "SASL_SSL"
      sasl.mechanisms: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPIC: "correction"
    SCHEMA_PATH: "/schemas/correction_step/output.avsc"
  SCRIBE_PRODUCER_CONFIG:
    CLASS: "apf.producers.KafkaProducer"
    PARAMS:
      bootstrap.servers: ""
      message.max.bytes: 6291456
      security.protocol: "SASL_SSL"
      sasl.mechanisms: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    SCHEMA_PATH: "/schemas/scribe_step/scribe.avsc"
    TOPIC: ""
  LOGGING_DEBUG: false
  FEATURE_FLAGS:
    PROMETHEUS: false
