apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multisurvey-step.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "multisurvey-step.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "multisurvey-step.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multisurvey-step.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.stepName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.envVariables | nindent 12 }}
          {{- if .Values.configYaml.enabled }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          {{- end}}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configYaml.enabled }}
      volumes:
        - name: config
          configMap:
            name: config-yaml
            items:
              - key: "config.yaml"
                path: "config.yaml"
      {{- end }}
