"""Golden-master regression test.

Pins the full periodogram output for a fixed light curve against a stored
baseline. Its purpose is to prove that the Phase 4A loop-move into Cython is a
*pure* refactor (numerically identical to the per-frequency Python loop).

The baseline is regenerated by running this file as a script:

    python tests/test_regression_golden.py --capture

Capture the baseline from the float32 build before Phase 4A. After the Phase 4B
precision change the output legitimately changes; recapture and note the diff in
benchmarks/RESULTS.md.
"""
import os
import numpy as np
import pytest

from P4J import MultiBandPeriodogram
from conftest import make_lightcurve

BASELINE = os.path.join(os.path.dirname(__file__), "baseline_mhaov.npz")

# Tolerance for the pure loop-move refactor. Ideally exact; allow float32 ULP
# slack to absorb any compiler reassociation under -ffast-math.
RTOL = 0.0
ATOL = 1e-6


def _fixed_periodogram():
    """A single, fully-deterministic multiband evaluation."""
    mjd, mag, err, fid = make_lightcurve(0.2734, n_points=400, seed=123, bands=("g", "r"))
    p = MultiBandPeriodogram(method="MHAOV")
    p.set_data(mjd, mag, err, fid)
    # Bounded grid: keeps the committed golden baseline small (~60 kB) while
    # still spanning the true peak at f0 ~ 3.66.
    p.frequency_grid_evaluation(fmin=0.05, fmax=8.0, fresolution=2e-3)
    freq, per = p.get_periodogram()
    return np.asarray(freq), np.asarray(per)


def capture():
    freq, per = _fixed_periodogram()
    np.savez_compressed(BASELINE, freq=freq, per=per)
    print(f"wrote baseline: {BASELINE}  grid={freq.size}  per[max]={per.max():.6g}")


@pytest.mark.skipif(not os.path.exists(BASELINE), reason="no golden baseline captured yet")
def test_periodogram_matches_baseline():
    data = np.load(BASELINE)
    freq, per = _fixed_periodogram()
    assert freq.size == data["freq"].size, "grid size changed"
    # frequency grid must be identical in value (dtype may widen in 4B)
    np.testing.assert_allclose(freq, data["freq"], rtol=0, atol=1e-9)
    np.testing.assert_allclose(per, data["per"], rtol=RTOL, atol=ATOL)


if __name__ == "__main__":
    import sys

    if "--capture" in sys.argv:
        capture()
    else:
        print("pass --capture to (re)write the baseline")
