# Default values for step_starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

stepName: ingestion-step 

namespace: ingestion-step

fullnameOverride: ""

image:
  repository: ghcr.io/alercebroker/ingestion_step
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: "image-pull-access"

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
          - matchExpressions:
            - key: nodegroup
              operator: In
              ## Override this value with the NodeGroup tag accordingly
              values:
              - staging-pipeline

imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""

envVariables:
  - name: CONFIG_FROM_YAML
    value: "True"

configYaml:
  enabled: true
  CONSUMER_CONFIG:
    CLASS: "apf.consumers.KafkaSchemalessConsumer"
    SCHEMA_PATH: "/schemas/surveys/lsst/v7_4_alert.avsc"
    PARAMS:
      bootstrap.servers: ""
      group.id: "ingestion-step"
      auto.offset.reset: "beginning"
      enable.partition.eof: false
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPICS: ["lsst"]
    consume.messages: 100
    consume.timeout: 10
  PRODUCER_CONFIG:
    CLASS: "apf.producers.KafkaSchemalessProducer"
    PARAMS:
      bootstrap.servers: ""
      message.max.bytes: 67108864
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPIC: "lsst-ingestion"
    STRICT: false
    SCHEMA_PATH: "/schemas/ingestion_step/lsst/output.avsc"
  METRICS_CONFIG:
    CLASS: "apf.metrics.KafkaMetricsProducer"
    PARAMS:
      PARAMS:
        bootstrap.servers: ""
        security.protocol: "SASL_SSL"
        sasl.mechanism: "SCRAM-SHA-512"
        sasl.username: ""
        sasl.password: ""
      TOPIC: "metrics"
      SCHEMA_PATH: "/schemas/lightcurve_step/metrics.json"
  SURVEY_STRATEGY: "lsst"
  FEATURE_FLAGS:
    USE_PROFILING: false
    PROMETHEUS: false
    SKIP_MJD_FILTER: true
  PSQL_CONFIG:
    HOST: ""
    USER: ""
    PASSWORD: ""
    PORT: ""
    DB_NAME: ""
    SCHEMA: ""







