from ingestion_step.core.types import Message
from ingestion_step.lsst.strategy import LsstStrategy

msgs: list[Message] = [
    {
        "alertId": 396950608281652,
        "cutoutDifference": None,
        "cutoutScience": None,
        "cutoutTemplate": None,
        "diaSource": {
            "diaSourceId": 396950608281652,
            "visit": 59150,
            "detector": 50,
            "diaObjectId": 396950608281652,
            "ssObjectId": 0,
            "parentDiaSourceId": 0,
            "midpointMjdTai": 57454.30994266204,
            "ra": 149.8167115884139,
            "raErr": 5.583191295954748e-07,
            "dec": 2.1992463849958255,
            "decErr": 5.790691943730053e-07,
            "ra_dec_Cov": -2.554766777158033e-16,
            "x": 591.09619140625,
            "xErr": 0.012368046678602695,
            "y": 1151.2418212890625,
            "yErr": 0.011959286406636238,
            "x_y_Cov": float("nan"),
            "centroid_flag": False,
            "apFlux": 384.9031677246094,
            "apFluxErr": 62.968265533447266,
            "apFlux_flag": False,
            "apFlux_flag_apertureTruncated": False,
            "is_negative": False,
            "snr": 15.516036987304688,
            "psfFlux": 290.4140625,
            "psfFluxErr": 33.04096984863281,
            "psfRa": float("nan"),
            "psfRaErr": float("nan"),
            "psfDec": float("nan"),
            "psfDecErr": float("nan"),
            "psfFlux_psfRa_Cov": float("nan"),
            "psfFlux_psfDec_Cov": float("nan"),
            "psfRa_psfDec_Cov": float("nan"),
            "psfLnL": float("nan"),
            "psfChi2": 1910.3746337890625,
            "psfNdata": 1681,
            "psfFlux_flag": False,
            "psfFlux_flag_edge": False,
            "psfFlux_flag_noGoodPixels": False,
            "trailFlux": 457.63861083984375,
            "trailFluxErr": float("nan"),
            "trailRa": 149.8167775179173,
            "trailRaErr": float("nan"),
            "trailDec": 2.1992210298505115,
            "trailDecErr": float("nan"),
            "trailLength": 1.0460351705551147,
            "trailLengthErr": float("nan"),
            "trailAngle": 41.568580627441406,
            "trailAngleErr": float("nan"),
            "trailFlux_trailRa_Cov": float("nan"),
            "trailFlux_trailDec_Cov": float("nan"),
            "trailFlux_trailLength_Cov": float("nan"),
            "trailFlux_trailAngle_Cov": float("nan"),
            "trailRa_trailDec_Cov": float("nan"),
            "trailRa_trailLength_Cov": float("nan"),
            "trailRa_trailAngle_Cov": float("nan"),
            "trailDec_trailLength_Cov": float("nan"),
            "trailDec_trailAngle_Cov": float("nan"),
            "trailLength_trailAngle_Cov": float("nan"),
            "trailLnL": float("nan"),
            "trailChi2": float("nan"),
            "trailNdata": 0,
            "trail_flag_edge": False,
            "dipoleMeanFlux": 6481.14013671875,
            "dipoleMeanFluxErr": 20.96636962890625,
            "dipoleFluxDiff": 0.0,
            "dipoleFluxDiffErr": 41.9327392578125,
            "dipoleRa": float("nan"),
            "dipoleRaErr": float("nan"),
            "dipoleDec": float("nan"),
            "dipoleDecErr": float("nan"),
            "dipoleLength": 0.033619511872529984,
            "dipoleLengthErr": float("nan"),
            "dipoleAngle": 127.40485382080078,
            "dipoleAngleErr": float("nan"),
            "dipoleMeanFlux_dipoleFluxDiff_Cov": float("nan"),
            "dipoleMeanFlux_dipoleRa_Cov": float("nan"),
            "dipoleMeanFlux_dipoleDec_Cov": float("nan"),
            "dipoleMeanFlux_dipoleLength_Cov": float("nan"),
            "dipoleMeanFlux_dipoleAngle_Cov": float("nan"),
            "dipoleFluxDiff_dipoleRa_Cov": float("nan"),
            "dipoleFluxDiff_dipoleDec_Cov": float("nan"),
            "dipoleFluxDiff_dipoleLength_Cov": float("nan"),
            "dipoleFluxDiff_dipoleAngle_Cov": float("nan"),
            "dipoleRa_dipoleDec_Cov": float("nan"),
            "dipoleRa_dipoleLength_Cov": float("nan"),
            "dipoleRa_dipoleAngle_Cov": float("nan"),
            "dipoleDec_dipoleLength_Cov": float("nan"),
            "dipoleDec_dipoleAngle_Cov": float("nan"),
            "dipoleLength_dipoleAngle_Cov": float("nan"),
            "dipoleLnL": float("nan"),
            "dipoleChi2": 6.16653299331665,
            "dipoleNdata": 1197,
            "forced_PsfFlux_flag": False,
            "forced_PsfFlux_flag_edge": False,
            "forced_PsfFlux_flag_noGoodPixels": False,
            "snapDiffFlux": float("nan"),
            "snapDiffFluxErr": float("nan"),
            "fpBkgd": float("nan"),
            "fpBkgdErr": float("nan"),
            "ixx": 0.10198821127414703,
            "ixxErr": float("nan"),
            "iyy": 0.08760728687047958,
            "iyyErr": float("nan"),
            "ixy": 0.061538610607385635,
            "ixyErr": float("nan"),
            "ixx_iyy_Cov": float("nan"),
            "ixx_ixy_Cov": float("nan"),
            "iyy_ixy_Cov": float("nan"),
            "ixxPSF": 0.10731535404920578,
            "iyyPSF": 0.11006434261798859,
            "ixyPSF": 0.008812847547233105,
            "shape_flag": False,
            "shape_flag_no_pixels": False,
            "shape_flag_not_contained": False,
            "shape_flag_parent_source": False,
            "extendedness": 0.060713499784469604,
            "reliability": 0.3635614812374115,
            "band": "g",
            "dipoleFitAttempted": True,
            "pixelFlags": False,
            "pixelFlags_bad": False,
            "pixelFlags_cr": False,
            "pixelFlags_crCenter": False,
            "pixelFlags_edge": False,
            "pixelFlags_nodata": False,
            "pixelFlags_nodataCenter": False,
            "pixelFlags_interpolated": False,
            "pixelFlags_interpolatedCenter": False,
            "pixelFlags_offimage": False,
            "pixelFlags_saturated": False,
            "pixelFlags_saturatedCenter": False,
            "pixelFlags_suspect": False,
            "pixelFlags_suspectCenter": False,
            "pixelFlags_streak": False,
            "pixelFlags_streakCenter": False,
            "pixelFlags_injected": False,
            "pixelFlags_injectedCenter": False,
            "pixelFlags_injected_template": False,
            "pixelFlags_injected_templateCenter": False,
        },
        "prvDiaSources": None,
        "prvDiaForcedSources": [],
        "prvDiaNondetectionLimits": None,
        "diaObject": {
            "diaObjectId": 396950608281652,
            "ra": 149.8167115884139,
            "raErr": 5.583191295954748e-07,
            "dec": 2.1992463849958255,
            "decErr": 5.790691943730053e-07,
            "ra_dec_Cov": -2.554766777158033e-16,
            "radecMjdTai": 57454.30994266204,
            "pmRa": float("nan"),
            "pmRaErr": float("nan"),
            "pmDec": float("nan"),
            "pmDecErr": float("nan"),
            "parallax": float("nan"),
            "parallaxErr": float("nan"),
            "pmRa_pmDec_Cov": float("nan"),
            "pmRa_parallax_Cov": float("nan"),
            "pmDec_parallax_Cov": float("nan"),
            "pmParallaxLnL": float("nan"),
            "pmParallaxChi2": float("nan"),
            "pmParallaxNdata": 0,
            "u_psfFluxMean": float("nan"),
            "u_psfFluxMeanErr": float("nan"),
            "u_psfFluxSigma": float("nan"),
            "u_psfFluxChi2": float("nan"),
            "u_psfFluxNdata": 0,
            "u_fpFluxMean": float("nan"),
            "u_fpFluxMeanErr": float("nan"),
            "u_fpFluxSigma": float("nan"),
            "g_psfFluxMean": 290.4140625,
            "g_psfFluxMeanErr": 33.04096984863281,
            "g_psfFluxSigma": float("nan"),
            "g_psfFluxChi2": 0.0,
            "g_psfFluxNdata": 1,
            "g_fpFluxMean": float("nan"),
            "g_fpFluxMeanErr": float("nan"),
            "g_fpFluxSigma": float("nan"),
            "r_psfFluxMean": float("nan"),
            "r_psfFluxMeanErr": float("nan"),
            "r_psfFluxSigma": float("nan"),
            "r_psfFluxChi2": float("nan"),
            "r_psfFluxNdata": 0,
            "r_fpFluxMean": float("nan"),
            "r_fpFluxMeanErr": float("nan"),
            "r_fpFluxSigma": float("nan"),
            "i_psfFluxMean": float("nan"),
            "i_psfFluxMeanErr": float("nan"),
            "i_psfFluxSigma": float("nan"),
            "i_psfFluxChi2": float("nan"),
            "i_psfFluxNdata": 0,
            "i_fpFluxMean": float("nan"),
            "i_fpFluxMeanErr": float("nan"),
            "i_fpFluxSigma": float("nan"),
            "z_psfFluxMean": float("nan"),
            "z_psfFluxMeanErr": float("nan"),
            "z_psfFluxSigma": float("nan"),
            "z_psfFluxChi2": float("nan"),
            "z_psfFluxNdata": 0,
            "z_fpFluxMean": float("nan"),
            "z_fpFluxMeanErr": float("nan"),
            "z_fpFluxSigma": float("nan"),
            "y_psfFluxMean": float("nan"),
            "y_psfFluxMeanErr": float("nan"),
            "y_psfFluxSigma": float("nan"),
            "y_psfFluxChi2": float("nan"),
            "y_psfFluxNdata": 0,
            "y_fpFluxMean": float("nan"),
            "y_fpFluxMeanErr": float("nan"),
            "y_fpFluxSigma": float("nan"),
            "nearbyObj1": 0,
            "nearbyObj1Dist": float("nan"),
            "nearbyObj1LnP": float("nan"),
            "nearbyObj2": 0,
            "nearbyObj2Dist": float("nan"),
            "nearbyObj2LnP": float("nan"),
            "nearbyObj3": 0,
            "nearbyObj3Dist": float("nan"),
            "nearbyObj3LnP": float("nan"),
            "u_psfFluxErrMean": float("nan"),
            "g_psfFluxErrMean": 33.04096984863281,
            "r_psfFluxErrMean": float("nan"),
            "i_psfFluxErrMean": float("nan"),
            "z_psfFluxErrMean": float("nan"),
            "y_psfFluxErrMean": float("nan"),
        },
        "ssObject": None,
    }
]


def test_precision_lsst():
    data = LsstStrategy.parse(msgs)

    for i, msg in enumerate(msgs):
        assert data["sources"]["psfFlux"][i] == msg["diaSource"]["psfFlux"]

        detections_lsst_dict = data["sources"][
            [
                "oid",
                "sid",
                "measurement_id",
                "parentDiaSourceId",
                "psfFlux",
                "psfFluxErr",
                "psfFlux_flag",
                "psfFlux_flag_edge",
                "psfFlux_flag_noGoodPixels",
            ]
        ].to_dict("records")

        assert detections_lsst_dict[i]["psfFlux"] == msg["diaSource"]["psfFlux"]
