import pandas as pd

db_sql_detection_schema = {
    "oid": pd.Int64Dtype(),
    "parent_candid": pd.Int64Dtype(),
    "measurement_id": pd.Int64Dtype(),
    "has_stamp": pd.BooleanDtype(),
    "pid": pd.Int64Dtype(),
    "isdiffpos": pd.Int64Dtype(),
    "ra": pd.Float64Dtype(),
    "dec": pd.Float64Dtype(),
    "band": pd.Int64Dtype(),
    "mjd": pd.Float64Dtype(),
    "forced": pd.BooleanDtype(),
    "new": pd.BooleanDtype(),
    "drbversion": pd.StringDtype(),
    "corrected": pd.BooleanDtype(),
    "magapbig": pd.Float64Dtype(),
    "dubious": pd.BooleanDtype(),
    "magap": pd.Float64Dtype(),
    "sigmagapbig": pd.Float64Dtype(),
    "sigmagap": pd.Float64Dtype(),
    "rfid": pd.Int64Dtype(),
    "distnr": pd.Float64Dtype(),
    "diffmaglim": pd.Float64Dtype(),
    "rb": pd.Float64Dtype(),
    "rbversion": pd.StringDtype(),
    "nid": pd.Int32Dtype(),
    "drb": pd.Float64Dtype(),
    "e_mag_corr": pd.Float64Dtype(),
    "e_mag_corr_ext": pd.Float64Dtype(),
    "mag_corr": pd.Float64Dtype(),
    "mag": pd.Float64Dtype(),
    "e_mag": pd.Float64Dtype(),
    "e_ra": pd.Float64Dtype(),
    "e_dec": pd.Float64Dtype(),
    "sid": pd.Int32Dtype(),
    "tid": pd.Int32Dtype(),
}
