FROM python:3.8 as builder
ENV NUMEXPR_MAX_THREADS=1
MAINTAINER ALeRCE
ARG GH_TOKEN
WORKDIR /app/
RUN pip install poetry
COPY ./poetry.lock ./pyproject.toml /app/
RUN poetry config virtualenvs.create false
RUN poetry config http-basic.git alerceadmin ${GH_TOKEN}
RUN poetry install --no-interaction --without=dev --with=toretto --no-root

FROM builder
COPY ./lc_classification /app/lc_classification
COPY ./scripts /app/scripts
COPY ./README.md /app/
COPY ./settings.py /app/settings.py
COPY ./schemas.py /app/schemas.py
RUN poetry install --no-interaction --only-root
CMD ["poetry", "run", "python", "scripts/run_step.py"]
