## IMPORTANT ##
## This Dockerfile MUST be built with the context of the monorepo root directory
FROM python:3.8 as builder
ENV NUMEXPR_MAX_THREADS=1
MAINTAINER ALeRCE
ARG GH_TOKEN={GH_TOKEN}
WORKDIR /app/
RUN pip install poetry
COPY ./lc_classification_step/poetry.lock ./lc_classification_step/pyproject.toml /app/
COPY ./libs/alerce_classifiers /libs/alerce_classifiers
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --without=dev --with=toretto --no-root

FROM builder
COPY ./lc_classification_step/lc_classification /app/lc_classification
COPY ./lc_classification_step/scripts /app/scripts
COPY ./lc_classification_step/README.md /app/
COPY ./lc_classification_step/settings.py /app/settings.py
COPY ./lc_classification_step/schemas.py /app/schemas.py
RUN poetry install --no-interaction --only-root
CMD ["poetry", "run", "python", "scripts/run_step.py"]
