version: "3"
services:
  lc_classification:
    build: .
    environment:
      - DB_ENGINE=postgres
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - CONSUMER_TOPICS=features
      - CONSUMER_SERVER=${CONSUMER_SERVER}
      - CONSUMER_GROUP_ID=lc_classification_consumer_batch
      - PRODUCER_TOPIC=lc_classification_batch
      - PRODUCER_SERVER=${PRODUCER_SERVER}
      - STEP_VERSION=lc_classification.0.1_dev
      - FEATURE_VERSION=lc_classification.0.1_dev
      - METRICS_HOST=${METRICS_HOST}
      - METRICS_TOPIC=${METRICS_TOPIC}
      - CONSUME_TIMEOUT=60
      - CONSUME_MESSAGES=1000
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: /bin/bash
