'lc': {
  use_lightcurves_general: true,
}

'lc_mta': {
  use_lightcurves_general: true,
  online_opt_tt_general: true,
}

'md': {
  use_metadata_general: true,
  use_QT_general: true,
}

'feat': {
  use_features_general: true,
  use_QT_general: true,
}

'feat_mta': {
  use_features_general: true,
  use_QT_general: true,
  online_opt_tt_general: true,
}

'md_feat': {
  use_metadata_general: true,
  use_features_general: true,
  use_QT_general: true,
}

'md_feat_mta': {
  use_metadata_general: true,
  use_features_general: true,
  use_QT_general: true,
  online_opt_tt_general: true,
}

'lc_md': {
  use_lightcurves_general: true,
  use_metadata_general: true,
  use_QT_general: true,
}

'lc_md_mta': {
  use_lightcurves_general: true,
  use_metadata_general: true,
  use_QT_general: true,
  online_opt_tt_general: true,
}

'lc_md_feat': {
  use_lightcurves_general: true,
  use_metadata_general: true,
  use_features_general: true,
  use_QT_general: true,
}

'lc_md_feat_mta': {
  use_lightcurves_general: true,
  use_metadata_general: true,
  use_features_general: true,
  use_QT_general: true,
  online_opt_tt_general: true,
}

'lc_md_feat_mta_ireyes': {
  use_lightcurves_general: true,
  use_metadata_general: true,
  use_features_general: true,
  use_QT_general: true,
  online_opt_tt_general: true,
}

