"""tables

Revision ID: 0e93a429fb77
Revises: 38844166227a
Create Date: 2020-07-01 14:59:11.887136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e93a429fb77'
down_revision = '38844166227a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('oid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ndethist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ncovhist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jdstarthist', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jdendhist', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('corrected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stellar', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ndet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('g_r_max', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g_r_max_corr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g_r_mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g_r_mean_corr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('meanra', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('meandec', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sigmara', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sigmadec', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deltajd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('firstmjd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lastmjd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('oid', name='object_pkey')
    )
    # ### end Alembic commands ###
