"""tables

Revision ID: 21f58a5309c2
Revises: 649d08de5b36
Create Date: 2020-07-01 21:09:50.371339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f58a5309c2'
down_revision = '649d08de5b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
