"""tables

Revision ID: 2eeef1b76d1e
Revises: 681926cb56d3
Create Date: 2020-07-01 18:40:57.280730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eeef1b76d1e'
down_revision = '681926cb56d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
