"""tables

Revision ID: 4987e68d2808
Revises: 54c7cec4d6fc
Create Date: 2020-07-01 15:34:44.468325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4987e68d2808'
down_revision = '54c7cec4d6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaia_ztf',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('candid', sa.String(), nullable=False),
    sa.Column('neargaia', sa.Float(), nullable=False),
    sa.Column('neargaiabright', sa.Float(), nullable=False),
    sa.Column('maggaia', sa.Float(), nullable=False),
    sa.Column('maggaiabright', sa.Float(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('oid', 'candid')
    )
    op.create_table('pipeline',
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('step_id_corr', sa.String(), nullable=False),
    sa.Column('step_id_feat', sa.String(), nullable=False),
    sa.Column('step_id_clf', sa.String(), nullable=False),
    sa.Column('step_id_out', sa.String(), nullable=False),
    sa.Column('step_id_stamp', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_id')
    )
    op.create_table('ps1_ztf',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('candid', sa.Integer(), nullable=False),
    sa.Column('objectidps1', sa.Float(), nullable=False),
    sa.Column('sgmag1', sa.Float(), nullable=False),
    sa.Column('srmag1', sa.Float(), nullable=False),
    sa.Column('simag1', sa.Float(), nullable=False),
    sa.Column('szmag1', sa.Float(), nullable=False),
    sa.Column('sgscore1', sa.Float(), nullable=False),
    sa.Column('distpsnr1', sa.Float(), nullable=False),
    sa.Column('objectidps2', sa.Float(), nullable=False),
    sa.Column('sgmag2', sa.Float(), nullable=False),
    sa.Column('srmag2', sa.Float(), nullable=False),
    sa.Column('simag2', sa.Float(), nullable=False),
    sa.Column('szmag2', sa.Float(), nullable=False),
    sa.Column('sgscore2', sa.Float(), nullable=False),
    sa.Column('distpsnr2', sa.Float(), nullable=False),
    sa.Column('objectidps3', sa.Float(), nullable=False),
    sa.Column('sgmag3', sa.Float(), nullable=False),
    sa.Column('srmag3', sa.Float(), nullable=False),
    sa.Column('simag3', sa.Float(), nullable=False),
    sa.Column('szmag3', sa.Float(), nullable=False),
    sa.Column('sgscore3', sa.Float(), nullable=False),
    sa.Column('distpsnr3', sa.Float(), nullable=False),
    sa.Column('nmtchps', sa.Integer(), nullable=True),
    sa.Column('unique1', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('oid', 'candid')
    )
    op.create_table('reference',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('rfid', sa.String(), nullable=True),
    sa.Column('candiid', sa.String(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('rcid', sa.Integer(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('magnr', sa.Float(), nullable=False),
    sa.Column('sigmagnr', sa.Float(), nullable=False),
    sa.Column('chinr', sa.Float(), nullable=False),
    sa.Column('sharpnr', sa.Float(), nullable=False),
    sa.Column('ranr', sa.Float(), nullable=True),
    sa.Column('decnr', sa.Float(), nullable=True),
    sa.Column('mjdstartref', sa.Float(), nullable=True),
    sa.Column('mjdendref', sa.Float(), nullable=True),
    sa.Column('nframesref', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('ss_ztf',
    sa.Column('oid', sa.String(), nullable=False),
    sa.Column('candid', sa.String(), nullable=True),
    sa.Column('ssdistnr', sa.Float(), nullable=False),
    sa.Column('ssmagnr', sa.Float(), nullable=False),
    sa.Column('ssnamenr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oid')
    )
    op.create_table('step',
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('ss_ztf')
    op.drop_table('reference')
    op.drop_table('ps1_ztf')
    op.drop_table('pipeline')
    op.drop_table('gaia_ztf')
    # ### end Alembic commands ###
