"""tables

Revision ID: 54c7cec4d6fc
Revises: ac00b85029a2
Create Date: 2020-07-01 15:26:29.991472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54c7cec4d6fc'
down_revision = 'ac00b85029a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('corrected', sa.Boolean(), nullable=True))
    op.add_column('detection', sa.Column('diffmaglim', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('distnr', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('drb', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('drbversion', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('dubious', sa.Boolean(), nullable=True))
    op.add_column('detection', sa.Column('has_stamp', sa.Boolean(), nullable=True))
    op.add_column('detection', sa.Column('isdiffpos', sa.Integer(), nullable=True))
    op.add_column('detection', sa.Column('jd', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('magapbig', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('nid', sa.Integer(), nullable=True))
    op.add_column('detection', sa.Column('parent_candid', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('pid', sa.Integer(), nullable=True))
    op.add_column('detection', sa.Column('rbversion', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('rfid', sa.String(), nullable=True))
    op.add_column('detection', sa.Column('sigmagapbig', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('sigmapsf_corr_ext', sa.Float(), nullable=True))
    op.add_column('detection', sa.Column('step_id_corr', sa.String(), nullable=True))
    op.drop_column('detection', 'sigmagap_corr')
    op.drop_column('detection', 'magap_corr')
    op.drop_column('detection', 'mjd')
    op.drop_column('detection', 'alert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection', sa.Column('alert', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('detection', sa.Column('mjd', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('detection', sa.Column('magap_corr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('detection', sa.Column('sigmagap_corr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('detection', 'step_id_corr')
    op.drop_column('detection', 'sigmapsf_corr_ext')
    op.drop_column('detection', 'sigmagapbig')
    op.drop_column('detection', 'rfid')
    op.drop_column('detection', 'rbversion')
    op.drop_column('detection', 'pid')
    op.drop_column('detection', 'parent_candid')
    op.drop_column('detection', 'nid')
    op.drop_column('detection', 'magapbig')
    op.drop_column('detection', 'jd')
    op.drop_column('detection', 'isdiffpos')
    op.drop_column('detection', 'has_stamp')
    op.drop_column('detection', 'dubious')
    op.drop_column('detection', 'drbversion')
    op.drop_column('detection', 'drb')
    op.drop_column('detection', 'distnr')
    op.drop_column('detection', 'diffmaglim')
    op.drop_column('detection', 'corrected')
    # ### end Alembic commands ###
