"""tables

Revision ID: 649d08de5b36
Revises: 2eeef1b76d1e
Create Date: 2020-07-01 18:42:11.412361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649d08de5b36'
down_revision = '2eeef1b76d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
