"""tables

Revision ID: 681926cb56d3
Revises: 4987e68d2808
Create Date: 2020-07-01 18:40:51.488497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681926cb56d3'
down_revision = '4987e68d2808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'magnitude_statistics', 'object', ['oid'], ['oid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magnitude_statistics', type_='foreignkey')
    # ### end Alembic commands ###
