"""tables

Revision ID: a0bf86c46b2e
Revises: 4595a7e9b671
Create Date: 2020-07-01 15:14:19.415931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0bf86c46b2e'
down_revision = '4595a7e9b671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magnitude_statistics', sa.Column('corrected', sa.Boolean(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('dm_first', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('dmdt_first', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('dt_first', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('firstmjd', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('lastmjd', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magfirst', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('maglast', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magmax', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magmean', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magmedian', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magmin', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magsigma', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('ndet', sa.Integer(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('ndubious', sa.Integer(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('sigmadm_first', sa.Float(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('stellar', sa.Boolean(), nullable=True))
    op.add_column('magnitude_statistics', sa.Column('step_id_corr', sa.String(), nullable=True))
    op.alter_column('magnitude_statistics', 'fid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('mag_first', table_name='magnitude_statistics')
    op.create_index('mag_first', 'magnitude_statistics', ['magfirst'], unique=False, postgresql_using='btree')
    op.drop_index('mag_last', table_name='magnitude_statistics')
    op.create_index('mag_last', 'magnitude_statistics', ['maglast'], unique=False, postgresql_using='btree')
    op.drop_index('mag_max', table_name='magnitude_statistics')
    op.create_index('mag_max', 'magnitude_statistics', ['magmax'], unique=False, postgresql_using='btree')
    op.drop_index('mag_mean', table_name='magnitude_statistics')
    op.create_index('mag_mean', 'magnitude_statistics', ['magmean'], unique=False, postgresql_using='btree')
    op.drop_index('mag_median', table_name='magnitude_statistics')
    op.create_index('mag_median', 'magnitude_statistics', ['magmedian'], unique=False, postgresql_using='btree')
    op.drop_index('mag_min', table_name='magnitude_statistics')
    op.create_index('mag_min', 'magnitude_statistics', ['magmin'], unique=False, postgresql_using='btree')
    op.drop_constraint('magnitude_statistics_oid_fkey', 'magnitude_statistics', type_='foreignkey')
    op.drop_column('magnitude_statistics', 'min_mag')
    op.drop_column('magnitude_statistics', 'sigma')
    op.drop_column('magnitude_statistics', 'last')
    op.drop_column('magnitude_statistics', 'median')
    op.drop_column('magnitude_statistics', 'max_mag')
    op.drop_column('magnitude_statistics', 'magnitude_type')
    op.drop_column('magnitude_statistics', 'mean')
    op.drop_column('magnitude_statistics', 'first')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magnitude_statistics', sa.Column('first', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('mean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('magnitude_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('magnitude_statistics', sa.Column('max_mag', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('median', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('last', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('sigma', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('magnitude_statistics', sa.Column('min_mag', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('magnitude_statistics_oid_fkey', 'magnitude_statistics', 'object', ['oid'], ['oid'])
    op.drop_index('mag_min', table_name='magnitude_statistics')
    op.create_index('mag_min', 'magnitude_statistics', ['min_mag'], unique=False)
    op.drop_index('mag_median', table_name='magnitude_statistics')
    op.create_index('mag_median', 'magnitude_statistics', ['median'], unique=False)
    op.drop_index('mag_mean', table_name='magnitude_statistics')
    op.create_index('mag_mean', 'magnitude_statistics', ['mean'], unique=False)
    op.drop_index('mag_max', table_name='magnitude_statistics')
    op.create_index('mag_max', 'magnitude_statistics', ['max_mag'], unique=False)
    op.drop_index('mag_last', table_name='magnitude_statistics')
    op.create_index('mag_last', 'magnitude_statistics', ['last'], unique=False)
    op.drop_index('mag_first', table_name='magnitude_statistics')
    op.create_index('mag_first', 'magnitude_statistics', ['first'], unique=False)
    op.alter_column('magnitude_statistics', 'fid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('magnitude_statistics', 'step_id_corr')
    op.drop_column('magnitude_statistics', 'stellar')
    op.drop_column('magnitude_statistics', 'sigmadm_first')
    op.drop_column('magnitude_statistics', 'ndubious')
    op.drop_column('magnitude_statistics', 'ndet')
    op.drop_column('magnitude_statistics', 'magsigma')
    op.drop_column('magnitude_statistics', 'magmin')
    op.drop_column('magnitude_statistics', 'magmedian')
    op.drop_column('magnitude_statistics', 'magmean')
    op.drop_column('magnitude_statistics', 'magmax')
    op.drop_column('magnitude_statistics', 'maglast')
    op.drop_column('magnitude_statistics', 'magfirst')
    op.drop_column('magnitude_statistics', 'lastmjd')
    op.drop_column('magnitude_statistics', 'firstmjd')
    op.drop_column('magnitude_statistics', 'dt_first')
    op.drop_column('magnitude_statistics', 'dmdt_first')
    op.drop_column('magnitude_statistics', 'dm_first')
    op.drop_column('magnitude_statistics', 'corrected')
    # ### end Alembic commands ###
