"""tables

Revision ID: ac00b85029a2
Revises: a0bf86c46b2e
Create Date: 2020-07-01 15:18:13.732449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac00b85029a2'
down_revision = 'a0bf86c46b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataquality',
    sa.Column('candid', sa.String(), nullable=False),
    sa.Column('oid', sa.String(), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('xpos', sa.Float(), nullable=False),
    sa.Column('ypos', sa.Float(), nullable=False),
    sa.Column('chipsf', sa.Float(), nullable=False),
    sa.Column('sky', sa.Float(), nullable=False),
    sa.Column('fwhm', sa.Float(), nullable=False),
    sa.Column('classtar', sa.Float(), nullable=False),
    sa.Column('mindtoedge', sa.Float(), nullable=False),
    sa.Column('seeratio', sa.Float(), nullable=False),
    sa.Column('aimage', sa.Float(), nullable=False),
    sa.Column('bimage', sa.Float(), nullable=False),
    sa.Column('aimagerat', sa.Float(), nullable=False),
    sa.Column('bimagerat', sa.Float(), nullable=False),
    sa.Column('nneg', sa.Integer(), nullable=False),
    sa.Column('nbad', sa.Integer(), nullable=False),
    sa.Column('sumrat', sa.Float(), nullable=False),
    sa.Column('scorr', sa.Float(), nullable=False),
    sa.Column('dsnrms', sa.Float(), nullable=False),
    sa.Column('ssnrms', sa.Float(), nullable=False),
    sa.Column('magzpsci', sa.Float(), nullable=False),
    sa.Column('magzpsciunc', sa.Float(), nullable=False),
    sa.Column('magzpscirms', sa.Float(), nullable=False),
    sa.Column('nmatches', sa.Integer(), nullable=False),
    sa.Column('clrcoeff', sa.Float(), nullable=False),
    sa.Column('clrcounc', sa.Float(), nullable=False),
    sa.Column('zpclrcov', sa.Float(), nullable=False),
    sa.Column('zpmed', sa.Float(), nullable=False),
    sa.Column('clrmed', sa.Float(), nullable=False),
    sa.Column('clrrms', sa.Float(), nullable=False),
    sa.Column('exptime', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('candid')
    )
    op.create_index('index_candid', 'dataquality', ['candid'], unique=False, postgresql_using='btree')
    op.create_index('index_fid', 'dataquality', ['fid'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_fid', table_name='dataquality')
    op.drop_index('index_candid', table_name='dataquality')
    op.drop_table('dataquality')
    # ### end Alembic commands ###
