"""tables

Revision ID: c7db5ec5b78e
Revises: 5261966a5cae
Create Date: 2020-07-01 21:11:13.912666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7db5ec5b78e'
down_revision = '5261966a5cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
