import numpy as np
import pandas as pd

fp_hist_schema = {
    "ra": np.float64,
    "dec": np.float64,
    "message_id": pd.Int64Dtype,
    "objectId": pd.Int64Dtype,
    "parent_candid": pd.Int64Dtype,
    "has_stamp": pd.BooleanDtype,
    "forced": pd.BooleanDtype,
    "field": pd.Int32Dtype,
    "rcid": pd.Int32Dtype,
    "fid": np.int32,
    "pid": np.int64,
    "rfid": np.int64,
    "sciinpseeing": np.float64,
    "scibckgnd": np.float64,
    "scisigpix": np.float64,
    "magzpsci": np.float64,
    "magzpsciunc": np.float64,
    "magzpscirms": np.float64,
    "clrcoeff": np.float64,
    "clrcounc": np.float64,
    "exptime": np.float64,
    "adpctdif1": np.float64,
    "adpctdif2": np.float64,
    "diffmaglim": np.float64,
    "programid": np.int32,
    "jd": np.float64,
    "forcediffimflux": np.float64,
    "forcediffimfluxunc": np.float64,
    "procstatus": pd.StringDtype,
    "distnr": np.float64,
    "ranr": np.float64,
    "decnr": np.float64,
    "magnr": np.float64,
    "sigmagnr": np.float64,
    "chinr": np.float64,
    "sharpnr": np.float64,
}
