import pandas as pd

fp_hist_schema = {
    "ra": pd.Float64Dtype,
    "dec": pd.Float64Dtype,
    "message_id": pd.Int64Dtype,
    "objectId": pd.StringDtype,
    "parent_candid": pd.Int64Dtype,
    "has_stamp": pd.BooleanDtype,
    "forced": pd.BooleanDtype,
    "field": pd.Int32Dtype,
    "rcid": pd.Int32Dtype,
    "fid": pd.Int32Dtype,
    "pid": pd.Int64Dtype,
    "rfid": pd.Int64Dtype,
    "sciinpseeing": pd.Float64Dtype,
    "scibckgnd": pd.Float64Dtype,
    "scisigpix": pd.Float64Dtype,
    "magzpsci": pd.Float64Dtype,
    "magzpsciunc": pd.Float64Dtype,
    "magzpscirms": pd.Float64Dtype,
    "clrcoeff": pd.Float64Dtype,
    "clrcounc": pd.Float64Dtype,
    "exptime": pd.Float64Dtype,
    "adpctdif1": pd.Float64Dtype,
    "adpctdif2": pd.Float64Dtype,
    "diffmaglim": pd.Float64Dtype,
    "programid": pd.Int32Dtype,
    "jd": pd.Float64Dtype,
    "forcediffimflux": pd.Float64Dtype,
    "forcediffimfluxunc": pd.Float64Dtype,
    "procstatus": pd.StringDtype,
    "distnr": pd.Float64Dtype,
    "ranr": pd.Float64Dtype,
    "decnr": pd.Float64Dtype,
    "magnr": pd.Float64Dtype,
    "sigmagnr": pd.Float64Dtype,
    "chinr": pd.Float64Dtype,
    "sharpnr": pd.Float64Dtype,
}
