apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xmatch-step.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  class-prefix: {{ .Values.configmap.classPrefix }}
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  consumer-server: {{ .Values.configmap.consumerServer }}
  consumer-group-id: {{ .Values.configmap.consumerGroupId | default (printf "%s" (include "xmatch-step.fullname" .)) }}
  producer-topic: {{ .Values.configmap.producerTopic }}
  producer-server: {{ .Values.configmap.producerServer }}
  producer-message-max-bytes: "{{ .Values.configmap.producerMessageMaxBytes }}"
  metrics-topic: {{ .Values.configmap.metricsTopic }}
  metrics-server: {{ .Values.configmap.metricsServer }}
  step-version: {{ .Chart.AppVersion }}
  retries: "{{ .Values.configmap.retries }}"
  retry-interval: "{{ .Values.configmap.retryInterval }}"
  consume-timeout: "{{ .Values.configmap.consumeTimeout }}"
  consume-messages: "{{ .Values.configmap.consumeMessages }}"
  scribe-server: {{ .Values.configmap.scribeServer }}
  scribe-topic: {{ .Values.configmap.scribeTopic }}
  skip-xmatch: '{{ .Values.configmap.skipXmatch }}'
