"""Offline ZTF feature LUTs (local fixture).

Stand-in for the DB feature_name_lut / feature_version_lut (sid=0), which are
empty (FLOW §3d). Generated by scripts/offline_generate_feature_lut.py and
checked in as static data. Ids are offline's own until the DB LUT is seeded;
the shape and rules match production, the id VALUES reconcile later.
"""
import logging

log = logging.getLogger(__name__)

# {feature_id: band-less feature_name}, sid=0. Ids 0..N-1 by sorted name.
# Generated: scripts/offline_generate_feature_lut.py --oid 36028941624528297
FEATURE_NAME_LUT = {
    0: 'Amplitude',
    1: 'AndersonDarling',
    2: 'Autocor_length',
    3: 'Beyond1Std',
    4: 'Con',
    5: 'Coordinate_x',
    6: 'Coordinate_y',
    7: 'Coordinate_z',
    8: 'Eta_e',
    9: 'ExcessVar',
    10: 'GP_DRW_sigma',
    11: 'GP_DRW_tau',
    12: 'Gskew',
    13: 'Harmonics_chi',
    14: 'Harmonics_mag_1',
    15: 'Harmonics_mag_2',
    16: 'Harmonics_mag_3',
    17: 'Harmonics_mag_4',
    18: 'Harmonics_mag_5',
    19: 'Harmonics_mag_6',
    20: 'Harmonics_mag_7',
    21: 'Harmonics_mse',
    22: 'Harmonics_phase_2',
    23: 'Harmonics_phase_3',
    24: 'Harmonics_phase_4',
    25: 'Harmonics_phase_5',
    26: 'Harmonics_phase_6',
    27: 'Harmonics_phase_7',
    28: 'IAR_phi',
    29: 'LinearTrend',
    30: 'MHPS_PN_flag',
    31: 'MHPS_high',
    32: 'MHPS_high_30',
    33: 'MHPS_low',
    34: 'MHPS_low_365',
    35: 'MHPS_non_zero',
    36: 'MHPS_ratio',
    37: 'MHPS_ratio_365_30',
    38: 'MaxSlope',
    39: 'Mean',
    40: 'Meanvariance',
    41: 'MedianAbsDev',
    42: 'MedianBRP',
    43: 'Multiband_period',
    44: 'PPE',
    45: 'PairSlopeTrend',
    46: 'PercentAmplitude',
    47: 'Period_band',
    48: 'Power_rate_1/2',
    49: 'Power_rate_1/3',
    50: 'Power_rate_1/4',
    51: 'Power_rate_2',
    52: 'Power_rate_3',
    53: 'Power_rate_4',
    54: 'Psi_CS',
    55: 'Psi_eta',
    56: 'Pvar',
    57: 'Q31',
    58: 'Rcs',
    59: 'SF_ML_amplitude',
    60: 'SF_ML_gamma',
    61: 'SPM_A',
    62: 'SPM_beta',
    63: 'SPM_chi',
    64: 'SPM_gamma',
    65: 'SPM_t0',
    66: 'SPM_tau_fall',
    67: 'SPM_tau_rise',
    68: 'Skew',
    69: 'SmallKurtosis',
    70: 'Std',
    71: 'StetsonK',
    72: 'TDE_decay',
    73: 'TDE_decay_chi',
    74: 'TDE_mag0',
    75: 'Timespan',
    76: 'W1-W2',
    77: 'W2-W3',
    78: 'W3-W4',
    79: 'color_variation',
    80: 'dbrightness_first_det_band',
    81: 'dbrightness_forced_phot_band',
    82: 'delta_period',
    83: 'distpsnr1',
    84: 'fleet_a',
    85: 'fleet_chi',
    86: 'fleet_m0',
    87: 'fleet_t0',
    88: 'fleet_w',
    89: 'g-W1',
    90: 'g-W2',
    91: 'g-W3',
    92: 'g-W4',
    93: 'g-r_max',
    94: 'g-r_max_corr',
    95: 'g-r_mean',
    96: 'g-r_mean_corr',
    97: 'last_brightness_before_band',
    98: 'max_brightness_after_band',
    99: 'max_brightness_before_band',
    100: 'mean_chinr',
    101: 'mean_distnr',
    102: 'mean_sharpnr',
    103: 'median_brightness_after_band',
    104: 'median_brightness_before_band',
    105: 'n_forced_phot_band_after',
    106: 'n_forced_phot_band_before',
    107: 'positive_fraction',
    108: 'ps_g-r',
    109: 'ps_i-z',
    110: 'ps_r-i',
    111: 'r-W1',
    112: 'r-W2',
    113: 'r-W3',
    114: 'r-W4',
    115: 'sgscore1',
    116: 'sigma_distnr',
    117: 'ulens_chi',
    118: 'ulens_fs',
    119: 'ulens_mag0',
    120: 'ulens_t0',
    121: 'ulens_tE',
    122: 'ulens_u0',
}

# {version_id: version_name}. Mirrors production's feature.version = the single
# feature-step package version (version("feature-step")). Update when the
# package version that produced these features changes.
FEATURE_VERSION_LUT = {
    0: '27.5.7a31',
}


def load_feature_name_lut() -> dict:
    """Return {feature_id: feature_name} — drop-in for database.get_feature_name_lut."""
    return dict(FEATURE_NAME_LUT)


def version_name_to_id(version_name) -> int:
    """Reverse-map a version string to its smallint id. Warn + return -1 if unknown."""
    rev = {name: vid for vid, name in FEATURE_VERSION_LUT.items()}
    if version_name not in rev:
        log.warning("Unknown feature version %r; not in FEATURE_VERSION_LUT", version_name)
        return -1
    return rev[version_name]


def default_version_name() -> str:
    """Canonical offline feature version: the latest entry in FEATURE_VERSION_LUT.

    Used as the fallback when `feature-step` is not pip-installed (offline runs
    from source), so version stamping never depends on importlib metadata.
    """
    return FEATURE_VERSION_LUT[max(FEATURE_VERSION_LUT)]
