"""Offline ZTF feature LUTs (local fixture).

Stand-in for the DB feature_name_lut / feature_version_lut (sid=0), which are
empty (FLOW §3d). Generated by scripts/offline_generate_feature_lut.py and
checked in as static data. Ids are offline's own until the DB LUT is seeded;
the shape and rules match production, the id VALUES reconcile later.

`render_seed_sql()` is the single source of truth for ztf_feature_luts_seed.sql;
regenerate that file from here rather than hand-editing it.
"""
import logging

log = logging.getLogger(__name__)

SCHEMA = "multisurvey_ztf"

# {feature_id: band-less feature_name}, sid=0. Ids 0..N-1 in EXTRACTOR (natural)
# order — the order the ZTF composite emits features, NOT alphabetical.
# Generated: scripts/offline_generate_feature_lut.py --oid 36028941624528297
FEATURE_NAME_LUT = {
    0: 'g-r_mean',
    1: 'g-r_max',
    2: 'g-r_mean_corr',
    3: 'g-r_max_corr',
    4: 'W1-W2',
    5: 'W2-W3',
    6: 'W3-W4',
    7: 'g-W1',
    8: 'r-W1',
    9: 'g-W2',
    10: 'r-W2',
    11: 'g-W3',
    12: 'r-W3',
    13: 'g-W4',
    14: 'r-W4',
    15: 'sgscore1',
    16: 'distpsnr1',
    17: 'ps_g-r',
    18: 'ps_r-i',
    19: 'ps_i-z',
    20: 'MHPS_ratio',
    21: 'MHPS_low',
    22: 'MHPS_high',
    23: 'MHPS_non_zero',
    24: 'MHPS_PN_flag',
    25: 'MHPS_ratio_365_30',
    26: 'MHPS_low_365',
    27: 'MHPS_high_30',
    28: 'GP_DRW_sigma',
    29: 'GP_DRW_tau',
    30: 'Multiband_period',
    31: 'PPE',
    32: 'Period_band',
    33: 'delta_period',
    34: 'Power_rate_1/4',
    35: 'Power_rate_1/3',
    36: 'Power_rate_1/2',
    37: 'Power_rate_2',
    38: 'Power_rate_3',
    39: 'Power_rate_4',
    40: 'Psi_CS',
    41: 'Psi_eta',
    42: 'Harmonics_mse',
    43: 'Harmonics_chi',
    44: 'Harmonics_mag_1',
    45: 'Harmonics_mag_2',
    46: 'Harmonics_phase_2',
    47: 'Harmonics_mag_3',
    48: 'Harmonics_phase_3',
    49: 'Harmonics_mag_4',
    50: 'Harmonics_phase_4',
    51: 'Harmonics_mag_5',
    52: 'Harmonics_phase_5',
    53: 'Harmonics_mag_6',
    54: 'Harmonics_phase_6',
    55: 'Harmonics_mag_7',
    56: 'Harmonics_phase_7',
    57: 'Amplitude',
    58: 'AndersonDarling',
    59: 'Autocor_length',
    60: 'Beyond1Std',
    61: 'Con',
    62: 'Eta_e',
    63: 'Gskew',
    64: 'MaxSlope',
    65: 'Mean',
    66: 'Meanvariance',
    67: 'MedianAbsDev',
    68: 'MedianBRP',
    69: 'PairSlopeTrend',
    70: 'PercentAmplitude',
    71: 'Q31',
    72: 'Rcs',
    73: 'Skew',
    74: 'SmallKurtosis',
    75: 'Std',
    76: 'StetsonK',
    77: 'Pvar',
    78: 'ExcessVar',
    79: 'SF_ML_amplitude',
    80: 'SF_ML_gamma',
    81: 'IAR_phi',
    82: 'LinearTrend',
    83: 'SPM_A',
    84: 'SPM_t0',
    85: 'SPM_gamma',
    86: 'SPM_beta',
    87: 'SPM_tau_rise',
    88: 'SPM_tau_fall',
    89: 'SPM_chi',
    90: 'SPM_mjd_ref',
    91: 'TDE_decay',
    92: 'TDE_decay_chi',
    93: 'TDE_mag0',
    94: 'TDE_mjd_ref',
    95: 'fleet_a',
    96: 'fleet_w',
    97: 'fleet_chi',
    98: 'fleet_m0',
    99: 'fleet_t0',
    100: 'fleet_mjd_ref',
    101: 'color_variation',
    102: 'positive_fraction',
    103: 'n_forced_phot_band_before',
    104: 'dbrightness_first_det_band',
    105: 'dbrightness_forced_phot_band',
    106: 'last_brightness_before_band',
    107: 'max_brightness_before_band',
    108: 'median_brightness_before_band',
    109: 'n_forced_phot_band_after',
    110: 'max_brightness_after_band',
    111: 'median_brightness_after_band',
    112: 'ulens_u0',
    113: 'ulens_tE',
    114: 'ulens_fs',
    115: 'ulens_chi',
    116: 'ulens_t0',
    117: 'ulens_mag0',
    118: 'ulens_mjd_ref',
    119: 'mean_distnr',
    120: 'sigma_distnr',
    121: 'mean_sharpnr',
    122: 'mean_chinr',
    123: 'Timespan',
    124: 'Coordinate_x',
    125: 'Coordinate_y',
    126: 'Coordinate_z',
}

# {version_id: version_name}. Mirrors production's feature.version = the single
# feature-step package version (version("feature-step")). Update when the
# package version that produced these features changes.
# version_id starts at 1, matching what production actually assigns:
# features.database.get_or_create_version_id inserts COALESCE(MAX(version_id), 0) + 1,
# and the column has no default or sequence, so the number is whatever the inserter
# supplies. Seeding 0 here (as the first version of this fixture did) made the same
# version_name resolve to 0 in multisurvey_ztf and 1 in multisurvey — invalidating
# every cross-schema comparison keyed on version_id.
FEATURE_VERSION_LUT = {
    1: '27.5.7a31',
}


def load_feature_name_lut() -> dict:
    """Return {feature_id: feature_name} — drop-in for database.get_feature_name_lut."""
    return dict(FEATURE_NAME_LUT)


def version_name_to_id(version_name) -> int:
    """Reverse-map a version string to its smallint id. Warn + return -1 if unknown."""
    rev = {name: vid for vid, name in FEATURE_VERSION_LUT.items()}
    if version_name not in rev:
        log.warning("Unknown feature version %r; not in FEATURE_VERSION_LUT", version_name)
        return -1
    return rev[version_name]


def default_version_name() -> str:
    """Canonical offline feature version: the latest entry in FEATURE_VERSION_LUT.

    Used as the fallback when `feature-step` is not pip-installed (offline runs
    from source), so version stamping never depends on importlib metadata.
    """
    return FEATURE_VERSION_LUT[max(FEATURE_VERSION_LUT)]


def _sql_str(value: str) -> str:
    """Single-quote a SQL string literal, escaping embedded quotes."""
    return "'" + value.replace("'", "''") + "'"


def render_seed_sql() -> str:
    """Render the idempotent ZTF feature LUT seed from the fixture (single source
    of truth). Do not hand-edit ztf_feature_luts_seed.sql; regenerate from here."""
    n = len(FEATURE_NAME_LUT)
    lines = [
        "-- ZTF feature LUT seed (sid=0, tid=0).",
        "-- Generated from feature_step/features/offline/feature_lut.py (single source of truth).",
        "-- Do not hand-edit; regenerate via feature_lut.render_seed_sql().",
        '-- Run with:  psql "<conn>" -f ztf_feature_luts_seed.sql   (needs INSERT privileges, not readonly_user)',
        "-- Or open this file in your SQL client and execute (avoids copy-paste mangling).",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- 0. (optional) inspect current state before seeding",
        "-- ---------------------------------------------------------------------------",
        f"-- SELECT version_id, version_name, sid, tid FROM {SCHEMA}.feature_version_lut ORDER BY sid, version_id;",
        f"-- SELECT feature_id, feature_name, sid, tid FROM {SCHEMA}.feature_name_lut WHERE sid = 0 ORDER BY feature_id;",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- 1. feature_version_lut  (version_id namespaced by sid, lookups are by version_name)",
        "--    NOTE: ids follow the production get_or_create convention (start at 1),",
        "--    so the same version_name resolves to the same id here and in multisurvey.",
        "-- ---------------------------------------------------------------------------",
        f"INSERT INTO {SCHEMA}.feature_version_lut (version_id, version_name, sid, tid) VALUES",
    ]
    vrows = [
        f"({vid}, {_sql_str(vname)}, 0, 0)"
        for vid, vname in sorted(FEATURE_VERSION_LUT.items())
    ]
    lines.append(",\n".join(vrows))
    lines.append("ON CONFLICT (version_id, sid) DO NOTHING;")
    lines.append("")
    lines.append("-- ---------------------------------------------------------------------------")
    lines.append(f"-- 2. feature_name_lut  ({n} band-less ZTF feature names, band lives in feature.band)")
    lines.append("--    Ids in extractor (natural) emission order, NOT alphabetical.")
    lines.append("-- ---------------------------------------------------------------------------")
    lines.append(f"INSERT INTO {SCHEMA}.feature_name_lut (feature_id, feature_name, sid, tid) VALUES")
    frows = [
        f"({fid}, {_sql_str(fname)}, 0, 0)"
        for fid, fname in sorted(FEATURE_NAME_LUT.items())
    ]
    lines.append(",\n".join(frows))
    lines.append("ON CONFLICT (feature_id, sid) DO NOTHING;")
    lines.append("")
    return "\n".join(lines)
