#!/usr/bin/env python
"""apf command-line utility for administrative tasks."""
import os
import sys


def main():
    try:
        from apf.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
