from fastavro.utils import generate_one
import random


def _get_random_key(dictionary: dict):
    return random.choice(list(dictionary.keys()))


def features_ztf(force_empty_features=False, force_missing_features=False):
    FEATURES_SCHEMA = {
        "name": "features_record",
        "type": "record",
        "fields": [
            {"name": "Amplitude_1", "type": ["float", "null"]},
            {"name": "Amplitude_2", "type": ["float", "null"]},
            {"name": "AndersonDarling_1", "type": ["float", "null"]},
            {"name": "AndersonDarling_2", "type": ["float", "null"]},
            {"name": "Autocor_length_1", "type": ["float", "null"]},
            {"name": "Autocor_length_2", "type": ["float", "null"]},
            {"name": "Beyond1Std_1", "type": ["float", "null"]},
            {"name": "Beyond1Std_2", "type": ["float", "null"]},
            {"name": "Con_1", "type": ["float", "null"]},
            {"name": "Con_2", "type": ["float", "null"]},
            {"name": "Coordinate_x", "type": ["float", "null"]},
            {"name": "Coordinate_y", "type": ["float", "null"]},
            {"name": "Coordinate_z", "type": ["float", "null"]},
            {"name": "Eta_e_1", "type": ["float", "null"]},
            {"name": "Eta_e_2", "type": ["float", "null"]},
            {"name": "ExcessVar_1", "type": ["float", "null"]},
            {"name": "ExcessVar_2", "type": ["float", "null"]},
            {"name": "GP_DRW_sigma_1", "type": ["float", "null"]},
            {"name": "GP_DRW_sigma_2", "type": ["float", "null"]},
            {"name": "GP_DRW_tau_1", "type": ["float", "null"]},
            {"name": "GP_DRW_tau_2", "type": ["float", "null"]},
            {"name": "Gskew_1", "type": ["float", "null"]},
            {"name": "Gskew_2", "type": ["float", "null"]},
            {"name": "Harmonics_chi_1", "type": ["float", "null"]},
            {"name": "Harmonics_chi_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_1_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_1_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_2_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_2_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_3_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_3_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_4_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_4_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_5_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_5_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_6_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_6_2", "type": ["float", "null"]},
            {"name": "Harmonics_mag_7_1", "type": ["float", "null"]},
            {"name": "Harmonics_mag_7_2", "type": ["float", "null"]},
            {"name": "Harmonics_mse_1", "type": ["float", "null"]},
            {"name": "Harmonics_mse_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_2_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_2_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_3_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_3_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_4_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_4_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_5_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_5_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_6_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_6_2", "type": ["float", "null"]},
            {"name": "Harmonics_phase_7_1", "type": ["float", "null"]},
            {"name": "Harmonics_phase_7_2", "type": ["float", "null"]},
            {"name": "IAR_phi_1", "type": ["float", "null"]},
            {"name": "IAR_phi_2", "type": ["float", "null"]},
            {"name": "LinearTrend_1", "type": ["float", "null"]},
            {"name": "LinearTrend_2", "type": ["float", "null"]},
            {"name": "MHPS_PN_flag_1", "type": ["float", "null"]},
            {"name": "MHPS_PN_flag_2", "type": ["float", "null"]},
            {"name": "MHPS_high_1", "type": ["float", "null"]},
            {"name": "MHPS_high_2", "type": ["float", "null"]},
            {"name": "MHPS_low_1", "type": ["float", "null"]},
            {"name": "MHPS_low_2", "type": ["float", "null"]},
            {"name": "MHPS_non_zero_1", "type": ["float", "null"]},
            {"name": "MHPS_non_zero_2", "type": ["float", "null"]},
            {"name": "MHPS_ratio_1", "type": ["float", "null"]},
            {"name": "MHPS_ratio_2", "type": ["float", "null"]},
            {"name": "MHPS_high_30_1", "type": ["float", "null"]},
            {"name": "MHPS_high_30_2", "type": ["float", "null"]},
            {"name": "MHPS_low_365_1", "type": ["float", "null"]},
            {"name": "MHPS_low_365_2", "type": ["float", "null"]},
            {"name": "MHPS_ratio_365_30_1", "type": ["float", "null"]},
            {"name": "MHPS_ratio_365_30_2", "type": ["float", "null"]},
            {"name": "MaxSlope_1", "type": ["float", "null"]},
            {"name": "MaxSlope_2", "type": ["float", "null"]},
            {"name": "Mean_1", "type": ["float", "null"]},
            {"name": "Mean_2", "type": ["float", "null"]},
            {"name": "Meanvariance_1", "type": ["float", "null"]},
            {"name": "Meanvariance_2", "type": ["float", "null"]},
            {"name": "MedianAbsDev_1", "type": ["float", "null"]},
            {"name": "MedianAbsDev_2", "type": ["float", "null"]},
            {"name": "MedianBRP_1", "type": ["float", "null"]},
            {"name": "MedianBRP_2", "type": ["float", "null"]},
            {"name": "Multiband_period_12", "type": ["float", "null"]},
            {"name": "PPE_12", "type": ["float", "null"]},
            {"name": "PairSlopeTrend_1", "type": ["float", "null"]},
            {"name": "PairSlopeTrend_2", "type": ["float", "null"]},
            {"name": "PercentAmplitude_1", "type": ["float", "null"]},
            {"name": "PercentAmplitude_2", "type": ["float", "null"]},
            {"name": "Period_band_1", "type": ["float", "null"]},
            {"name": "Period_band_2", "type": ["float", "null"]},
            {"name": "Power_rate_1/2_12", "type": ["float", "null"]},
            {"name": "Power_rate_1/3_12", "type": ["float", "null"]},
            {"name": "Power_rate_1/4_12", "type": ["float", "null"]},
            {"name": "Power_rate_2_12", "type": ["float", "null"]},
            {"name": "Power_rate_3_12", "type": ["float", "null"]},
            {"name": "Power_rate_4_12", "type": ["float", "null"]},
            {"name": "Psi_CS_1", "type": ["float", "null"]},
            {"name": "Psi_CS_2", "type": ["float", "null"]},
            {"name": "Psi_eta_1", "type": ["float", "null"]},
            {"name": "Psi_eta_2", "type": ["float", "null"]},
            {"name": "Pvar_1", "type": ["float", "null"]},
            {"name": "Pvar_2", "type": ["float", "null"]},
            {"name": "Q31_1", "type": ["float", "null"]},
            {"name": "Q31_2", "type": ["float", "null"]},
            {"name": "Rcs_1", "type": ["float", "null"]},
            {"name": "Rcs_2", "type": ["float", "null"]},
            {"name": "SF_ML_amplitude_1", "type": ["float", "null"]},
            {"name": "SF_ML_amplitude_2", "type": ["float", "null"]},
            {"name": "SF_ML_gamma_1", "type": ["float", "null"]},
            {"name": "SF_ML_gamma_2", "type": ["float", "null"]},
            {"name": "SPM_A_1", "type": ["float", "null"]},
            {"name": "SPM_A_2", "type": ["float", "null"]},
            {"name": "SPM_beta_1", "type": ["float", "null"]},
            {"name": "SPM_beta_2", "type": ["float", "null"]},
            {"name": "SPM_chi_1", "type": ["float", "null"]},
            {"name": "SPM_chi_2", "type": ["float", "null"]},
            {"name": "SPM_gamma_1", "type": ["float", "null"]},
            {"name": "SPM_gamma_2", "type": ["float", "null"]},
            {"name": "SPM_t0_1", "type": ["float", "null"]},
            {"name": "SPM_t0_2", "type": ["float", "null"]},
            {"name": "SPM_tau_fall_1", "type": ["float", "null"]},
            {"name": "SPM_tau_fall_2", "type": ["float", "null"]},
            {"name": "SPM_tau_rise_1", "type": ["float", "null"]},
            {"name": "SPM_tau_rise_2", "type": ["float", "null"]},
            {"name": "Skew_1", "type": ["float", "null"]},
            {"name": "Skew_2", "type": ["float", "null"]},
            {"name": "SmallKurtosis_1", "type": ["float", "null"]},
            {"name": "SmallKurtosis_2", "type": ["float", "null"]},
            {"name": "Std_1", "type": ["float", "null"]},
            {"name": "Std_2", "type": ["float", "null"]},
            {"name": "StetsonK_1", "type": ["float", "null"]},
            {"name": "StetsonK_2", "type": ["float", "null"]},
            {"name": "TDE_decay_chi_1", "type": ["float", "null"]},
            {"name": "TDE_decay_chi_2", "type": ["float", "null"]},
            {"name": "TDE_decay_1", "type": ["float", "null"]},
            {"name": "TDE_decay_2", "type": ["float", "null"]},
            {"name": "Timespan", "type": ["float", "null"]},
            {"name": "W1-W2_12", "type": ["float", "null"]},
            {"name": "W2-W3_12", "type": ["float", "null"]},
            {"name": "W3-W4_12", "type": ["float", "null"]},
            {"name": "color_variation_12", "type": ["float", "null"]},
            {
                "name": "dbrightness_first_det_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "dbrightness_first_det_band_2",
                "type": ["float", "null"],
            },
            {
                "name": "dbrightness_forced_phot_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "dbrightness_forced_phot_band_2",
                "type": ["float", "null"],
            },
            {"name": "delta_period_1", "type": ["float", "null"]},
            {"name": "delta_period_2", "type": ["float", "null"]},
            {"name": "distpsnr1", "type": ["float", "null"]},
            {"name": "fleet_a_1", "type": ["float", "null"]},
            {"name": "fleet_a_2", "type": ["float", "null"]},
            {"name": "fleet_chi_1", "type": ["float", "null"]},
            {"name": "fleet_chi_2", "type": ["float", "null"]},
            {"name": "fleet_w_1", "type": ["float", "null"]},
            {"name": "fleet_w_2", "type": ["float", "null"]},
            {"name": "g-W1_12", "type": ["float", "null"]},
            {"name": "g-W2_12", "type": ["float", "null"]},
            {"name": "g-W3_12", "type": ["float", "null"]},
            {"name": "g-W4_12", "type": ["float", "null"]},
            {"name": "g-r_max_12", "type": ["float", "null"]},
            {"name": "g-r_mean_12", "type": ["float", "null"]},
            {
                "name": "last_brightness_before_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "last_brightness_before_band_2",
                "type": ["float", "null"],
            },
            {"name": "max_brightness_after_band_1", "type": ["float", "null"]},
            {"name": "max_brightness_after_band_2", "type": ["float", "null"]},
            {
                "name": "max_brightness_before_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "max_brightness_before_band_2",
                "type": ["float", "null"],
            },
            {"name": "mean_chinr_12", "type": ["float", "null"]},
            {"name": "mean_distnr_12", "type": ["float", "null"]},
            {"name": "mean_sharpnr_12", "type": ["float", "null"]},
            {
                "name": "median_brightness_after_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "median_brightness_after_band_2",
                "type": ["float", "null"],
            },
            {
                "name": "median_brightness_before_band_1",
                "type": ["float", "null"],
            },
            {
                "name": "median_brightness_before_band_2",
                "type": ["float", "null"],
            },
            {"name": "n_forced_phot_band_after_1", "type": ["float", "null"]},
            {"name": "n_forced_phot_band_after_2", "type": ["float", "null"]},
            {"name": "n_forced_phot_band_before_1", "type": ["float", "null"]},
            {"name": "n_forced_phot_band_before_2", "type": ["float", "null"]},
            {"name": "positive_fraction_1", "type": ["float", "null"]},
            {"name": "positive_fraction_2", "type": ["float", "null"]},
            {"name": "ps_g-r", "type": ["float", "null"]},
            {"name": "ps_r-i", "type": ["float", "null"]},
            {"name": "ps_i-z", "type": ["float", "null"]},
            {"name": "r-W1_12", "type": ["float", "null"]},
            {"name": "r-W2_12", "type": ["float", "null"]},
            {"name": "r-W3_12", "type": ["float", "null"]},
            {"name": "r-W4_12", "type": ["float", "null"]},
            {"name": "sgscore1", "type": ["float", "null"]},
            {"name": "sigma_distnr_12", "type": ["float", "null"]},
            {"name": "ulens_chi_1", "type": ["float", "null"]},
            {"name": "ulens_chi_2", "type": ["float", "null"]},
            {"name": "ulens_fs_1", "type": ["float", "null"]},
            {"name": "ulens_fs_2", "type": ["float", "null"]},
            {"name": "ulens_tE_1", "type": ["float", "null"]},
            {"name": "ulens_tE_2", "type": ["float", "null"]},
            {"name": "ulens_u0_1", "type": ["float", "null"]},
            {"name": "ulens_u0_2", "type": ["float", "null"]},
        ],
    }
    if force_empty_features:
        return {}
    features = generate_one(FEATURES_SCHEMA)
    if force_missing_features:
        for _ in range(random.randint(1, len(features))):
            try:
                key = _get_random_key(features)
                features[key] = None
            except KeyError:
                pass
    return features
