name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'alert_archiving_step/**'
      - '!alert_archiving_step/README.md'

jobs:
  alert_archiving_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
        sources-folder: 'alert_archiving_step'
        base-folder: 'alert_archiving_step'

  alert_archiving_step_unittest_cli:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.7'
      base-folder: 'alert_archiving_step'
      sources-folder: 'alert_archiving_step'
      test-folder: 'tests/cli'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

