name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "correction_step/**"
      - "!correction_step/README.md"

jobs:
  correction_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: "correction"
      base-folder: "correction_step"
  correction_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "correction_step"
      sources-folder: "correction"
      test-folder: "tests/unittests"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  correction_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "correction_step"
      sources-folder: "correction"
      test-folder: "tests/integration"
      codecov-flags: "" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  correction_step_build:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: correction_step --build-args=without:dev,test --dry-run
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
