name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "ingestion_step/**"
      - "!ingestion_step/README.md"

jobs:
  ingestion_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: "ingestion_step"
      sources-folder: "ingestion_step"
  ingestion_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "ingestion_step"
      python-version: "3.10"
      test-folder: "tests/unittest"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  ingestion_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "ingestion_step"
      python-version: "3.10"
      sources-folder: "ingestion_step"
      test-folder: "tests/integration"
      codecov-flags: "ingestion_step_integration" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  build-ingestion-dagger:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: ingestion_step --dry-run
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
