name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "lc_classifier/**"
      - "!lc_classifier/README.md"

jobs:
  lc_classifier_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: "lc_classifier"
      base-folder: "lc_classifier"
  lc_classifier_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: "3.10"
      base-folder: "lc_classifier"
      sources-folder: "lc_classifier"
      test-folder: "tests"
      codecov-flags: "lc_classifier" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
