name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "magstats_step/**"
      - "!magstats_step/README.md"

jobs:
  magstats_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: "magstats_step"
      base-folder: "magstats_step"
  magstats_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "magstats_step"
      python-version: "3.9"
      sources-folder: "magstats_step"
      test-folder: "tests/unittests"
      codecov-flags: "magstats_step_unittest"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  magstats_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "magstats_step"
      python-version: "3.9"
      sources-folder: "magstats_step"
      test-folder: "tests/integration"
      codecov-flags: "magstats_step_integration" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  build-magstats-dagger:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: magstats_step --dry-run
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
