name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'reflector_step/**'
      - '!reflector_step/README.md'

jobs:
  reflector_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
        sources-folder: 'reflector_step'
        base-folder: 'reflector_step'

  reflector_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
        python-version: '3.7'
        sources-folder: 'reflector_step'
        test-folder: 'tests/unittest'
        base-folder: 'reflector_step'
        codecov-flags: 'reflector_step_unittest'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  reflector_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.7'
      sources-folder: 'reflector_step'
      base-folder: 'reflector_step'
      test-folder: 'tests/integration'
      codecov-flags: 'reflector_step_integration'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
