name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'libs/survey_parser_plugins/**'
      - '!libs/survey_parser_plugins/README.md'

jobs:
  libs_survey_parser_plugins_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'libs/survey_parser_plugins'
      sources-folder: 'survey_parser_plugins'

  libs_survey_parser_plugins_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'libs/survey_parser_plugins'
      python-version: '3.10'
      sources-folder: 'survey_parser_plugins'
      test-folder: 'tests'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      sources-folder: 'sorting_hat_step'
  sorting_hat_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/unittest'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/integration'
      codecov-flags: 'sorting_hat_step_integration'  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
  build-sorting-hat-dagger:
    
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
        stage: staging
        extra-args: sorting_hat_step --dry-run
    secrets:
        GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  prv_candidates_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'prv_candidates_step'
      sources-folder: "prv_candidates_step"
  prv_candidates_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'prv_candidates_step'
      python-version: "3.8"
      test-folder: "tests/unit"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  prv_candidates_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'prv_candidates_step'
      python-version: '3.8'
      sources-folder: 'prv_candidates_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  build-prv-candidates-dagger:
    
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
        stage: staging
        extra-args: prv_candidates_step --dry-run
    secrets:
        GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
