name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "xmatch_step/**"
      - "!xmatch_step/README.md"

jobs:
  xmatch_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: "xmatch_step"
      sources-folder: "xmatch_step"
  xmatch_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "xmatch_step"
      python-version: "3.10"
      test-folder: "tests/unittest"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  xmatch_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "xmatch_step"
      python-version: "3.10"
      sources-folder: "xmatch_step"
      test-folder: "tests/integration"
      codecov-flags: "" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"

  build-xmatch-dagger:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: xmatch_step --dry-run
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
